"""Ticket 0531 — macros everywhere: manuscript numbers via generated macros.

Three layers of guard:

1. **Fragment vs artifact** — a sample of macro values is re-derived from the
   source CSVs by an INDEPENDENT parse and compared against the committed
   fragment. Never prose-vs-macro (tautological after the conversion: the
   prose IS the macro).
2. **Structural** — the manuscript preamble \\inputs the consolidated
   macros_manuscript.tex; the consolidated file defines no macro twice
   (tectonic would die on `\\newcommand` redefinition).
3. **Usage ratchet** — the UNexpanded body actually uses the macros (a
   revert to literals would pass layer 1 silently), and the review-listed
   stale literals are gone for good.
"""

import csv
import re
import statistics
from pathlib import Path

import pytest
from manuscript_source import MANUSCRIPT, body_raw, raw, strip_comments

from aedist.evaluate import reference_plant_count

pytestmark = pytest.mark.adherence

REPO_ROOT = Path(__file__).resolve().parent.parent
GEN = REPO_ROOT / "report" / "inputs" / "generated"
CONSOLIDATED = GEN / "macros_manuscript.tex"
REF_CSV = REPO_ROOT / "data" / "reference" / "vietnam_thermal_plants_v2_classified.csv"
XEVAL_CSV = REPO_ROOT / "experiments" / "derived" / "exp1_cross_eval.csv"
SWEEP_CSV = REPO_ROOT / "experiments" / "derived" / "aggregation_sweep.csv"
SCREEN_CSV = GEN / "tab_screen_validation_within_model.csv"
FUSION_CSV = GEN / "fusion_mvp.csv"


def _macro(name: str) -> str:
    """Value of \\newcommand{\\<name>}{...} in the consolidated file."""
    if not CONSOLIDATED.exists():
        pytest.skip(f"{CONSOLIDATED} not generated")
    m = re.search(
        rf"\\newcommand{{\\{re.escape(name)}}}{{([^}}]*)}}",
        CONSOLIDATED.read_text(encoding="utf-8"),
    )
    assert m, f"\\{name} not defined in {CONSOLIDATED.name}"
    return m.group(1)


def _screen_metric(metric: str) -> str:
    if not SCREEN_CSV.exists():
        pytest.skip(f"{SCREEN_CSV} not generated")
    for row in csv.DictReader(SCREEN_CSV.open(encoding="utf-8")):
        if row["metric"] == metric:
            return row["value"]
    raise AssertionError(f"metric {metric!r} not in {SCREEN_CSV.name}")


# --- 1. Fragment vs artifact (independent parse) ------------------------------
#
# Caveat for the two Screen* checks below: tab_screen_validation_within_model.csv
# is co-generated by the SAME script that emits the macro fragment, so these are
# drift guards (fragment regenerated without the CSV, or vice versa), not
# independent recomputations like the other checks in this section.


def test_screen_tau_cap_matches_artifact():
    assert _macro("ScreenTauCap") == _screen_metric("stratified_kendall_tau_cap_distinct")


def test_screen_binary_gap_matches_artifact():
    assert _macro("ScreenBinaryGap") == _screen_metric("per_model_binary_gap")


def test_screen_pooled_spearman_matches_artifact():
    """Ticket 0566: the manuscript's headline ρ (2 dp) tracks the pooled
    Spearman in the co-generated CSV (3 dp) — same drift-guard caveat as
    the two checks above."""
    csv_val = float(_screen_metric("pooled_spearman_cap_distinct"))
    assert _macro("ScreenPooledSpearman") == f"{csv_val:.2f}"


def test_exp1_f1_mean_matches_artifact():
    rows = list(csv.DictReader(XEVAL_CSV.open(encoding="utf-8")))
    mean = statistics.mean(float(r["accuracy_f1"]) for r in rows if r.get("accuracy_f1"))
    assert _macro("ExpOneFOneMean") == f"{mean:.2f}"


def test_exp1_status_acc_matches_artifact():
    rows = list(csv.DictReader(XEVAL_CSV.open(encoding="utf-8")))
    vals = [float(r["accuracy_status"]) for r in rows if r.get("accuracy_status") not in (None, "", "nan")]
    assert _macro("ExpOneStatusAcc") == f"{statistics.mean(vals):.2f}"


def test_reference_count_matches_csv_and_library():
    rows = list(csv.DictReader(REF_CSV.open(encoding="utf-8")))
    n = reference_plant_count()
    assert len(rows) == n, "CSV row count and reference_plant_count() diverge"
    assert _macro("NumRefPlants") == str(n)


def test_reference_coal_count_matches_csv():
    rows = list(csv.DictReader(REF_CSV.open(encoding="utf-8")))
    coal = sum(1 for r in rows if r["fuel"] == "coal")
    assert _macro("RefCoalCount") == str(coal)
    assert _macro("RefGasOilCount") == str(len(rows) - coal)


def test_agg_best_union_recall_matches_sweep():
    if not SWEEP_CSV.exists():
        pytest.skip(f"{SWEEP_CSV} not generated")
    for r in csv.DictReader(SWEEP_CSV.open(encoding="utf-8")):
        if (
            r["merge_method"] == "union"
            and r["diversity_rule"] == "cross_model_high"
            and r["pool_size"] == "3"
        ):
            assert _macro("AggBestUnionRecall") == f"{float(r['mean_recall']):.3f}"
            return
    raise AssertionError("best-union sweep cell not found")


def test_fusion_r2_e1_tp_matches_csv():
    if not FUSION_CSV.exists():
        pytest.skip(f"{FUSION_CSV} not generated")
    for r in csv.DictReader(FUSION_CSV.open(encoding="utf-8")):
        if r["regime"] == "E1" and r["rule"] == "r2_models":
            assert _macro("FusionRTwoEOneTP") == r["tp"]
            return
    raise AssertionError("E1/r2_models row not found in fusion_mvp.csv")


# --- 2. Structural -------------------------------------------------------------


def test_preamble_inputs_consolidated_macros():
    preamble = strip_comments(raw().split("\\begin{document}", 1)[0])
    assert "\\input{../../report/inputs/generated/macros_manuscript.tex}" in preamble, (
        "manuscript preamble must \\input the consolidated macros_manuscript.tex"
    )


def test_consolidated_macros_define_nothing_twice():
    if not CONSOLIDATED.exists():
        pytest.skip(f"{CONSOLIDATED} not generated")
    names = re.findall(
        r"\\newcommand{\\([A-Za-z]+)}", CONSOLIDATED.read_text(encoding="utf-8")
    )
    dups = sorted({n for n in names if names.count(n) > 1})
    assert not dups, f"duplicate macro definitions in {CONSOLIDATED.name}: {dups}"


def _fragment_paths() -> list[Path]:
    """Fragment files listed in MANUSCRIPT_MACRO_FRAGMENTS (experiments/render.mk).

    Items are either $(ANALYSIS_GEN)/<name>.tex literals or $(VARNAME)
    references whose `VARNAME := $(ANALYSIS_GEN)/<name>.tex` definition
    appears elsewhere in the same makefile.
    """
    mk = (REPO_ROOT / "experiments" / "render.mk").read_text(encoding="utf-8")
    block = re.search(
        r"MANUSCRIPT_MACRO_FRAGMENTS\s*:=\s*((?:[^\n]*\\\n)*[^\n]*)", mk
    )
    assert block, "MANUSCRIPT_MACRO_FRAGMENTS not found in render.mk"
    defs = dict(
        re.findall(r"^(\w+)\s*:?=\s*\$\(ANALYSIS_GEN\)/(\S+\.tex)\s*$", mk, re.M)
    )
    paths = []
    for item in re.findall(r"\$\((\w+)\)(/\S+\.tex)?", block.group(1)):
        var, tail = item
        if var == "ANALYSIS_GEN":
            assert tail, "bare $(ANALYSIS_GEN) without filename in fragment list"
            paths.append(GEN / tail.lstrip("/"))
        else:
            assert var in defs, f"cannot resolve $({var}) in fragment list"
            paths.append(GEN / defs[var])
    return paths


def test_consolidated_contains_every_fragment_verbatim():
    """A fragment regenerated without re-consolidation makes the committed
    macros_manuscript.tex stale — every committed fragment's full text must
    appear verbatim inside the consolidated file."""
    if not CONSOLIDATED.exists():
        pytest.skip(f"{CONSOLIDATED} not generated")
    fragments = _fragment_paths()
    assert len(fragments) == 17, f"expected 17 fragments, got {len(fragments)}"
    consolidated = CONSOLIDATED.read_text(encoding="utf-8")
    for frag in fragments:
        assert frag.exists(), f"fragment {frag.name} missing on disk"
        assert frag.read_text(encoding="utf-8") in consolidated, (
            f"fragment {frag.name} not verbatim in {CONSOLIDATED.name} — "
            "regenerated without re-consolidation?"
        )


def test_macro_names_are_letters_only():
    """Digits in a \\newcommand name silently truncate the TeX control word
    (the \\FusionNE1Runs lesson) — ban them in the consolidated file."""
    if not CONSOLIDATED.exists():
        pytest.skip(f"{CONSOLIDATED} not generated")
    bad = re.findall(
        r"\\newcommand{\\[A-Za-z]*[0-9][^}]*}",
        CONSOLIDATED.read_text(encoding="utf-8"),
    )
    assert not bad, f"macro names must be letters-only: {bad}"


# --- 3. Usage ratchet -----------------------------------------------------------


def _unexpanded_body() -> str:
    """The body WITHOUT macro expansion — what the author actually typed."""
    if not MANUSCRIPT.exists():
        pytest.skip("main.tex not found")
    return strip_comments(body_raw())


def test_body_uses_the_macros():
    text = _unexpanded_body()
    # \ScreenTauCap left the body with Annex E (ticket 0586); \ScreenPooledSpearman
    # left the manuscript entirely (ticket 0598 dropped the Spearman ρ regression
    # presentation — the screening conclusion is now carried by fig:reliability).
    for name in ("\\NumRefPlants", "\\ExpOneFOneMean", "\\AggUnionGainX"):
        assert name in text, f"manuscript body no longer uses {name} — literal crept back?"


def test_stale_review_literals_gone():
    """The 2026-06-11 review-listed stale numbers must never reappear."""
    text = _unexpanded_body()
    for needle in ("+0.215", "\\$2.85", "0.146", "(65 concordant"):
        assert needle not in text, f"stale literal {needle!r} back in main.tex"


def _exp2_section() -> str:
    """The §exp2 section body (unexpanded), bounded by its label."""
    text = _unexpanded_body()
    start = text.find("\\label{sec:exp2}")
    assert start != -1, "no \\label{sec:exp2} in main.tex body"
    nxt = re.search(r"\\section\*?\{", text[start:])
    return text[start : start + nxt.start()] if nxt else text[start:]


# Independent re-derivation of the §exp2 row-count and cost medians from the
# committed flat arm dirs — a DIFFERENT parse than the emitter (its own arm
# map, its own report filter), so the fragment is checked against the data,
# never against the emitter (ticket 0575).
_FLAT_ARM_DIRS = {
    "naive": "arm1_flat",
    "optimised": "arm2_flat",
    "arm3": "arm3_flat",
    "arm4": "arm4_flat",
}
_COST_FIELDS = ("total_cost_usd", "cost_usd")


def _flat_rows_cost(agent: str, arm: str) -> tuple[list[int], list[float]]:
    import json

    from aedist.extract import count_best_table_rows

    arm_dir = REPO_ROOT / "experiments" / "derived" / _FLAT_ARM_DIRS[arm]
    if not arm_dir.exists():
        pytest.skip(f"{arm_dir} not present")
    rows: list[int] = []
    costs: list[float] = []
    for jp in sorted(arm_dir.glob("*_run*.json")):
        meta = json.loads(jp.read_text(encoding="utf-8"))
        if meta.get("agent") != agent:
            continue
        if str(meta.get("classification") or "report") != "report":
            continue
        n = next((meta[k] for k in ("inventory_rows", "n_rows") if isinstance(meta.get(k), int)), None)
        if n is None:
            md = jp.with_suffix(".md")
            n = count_best_table_rows(md.read_text(encoding="utf-8")) if md.exists() else 0
        rows.append(int(n))
        cost = next((meta[k] for k in _COST_FIELDS if meta.get(k) is not None), None)
        if cost is not None:
            costs.append(float(cost))
    return rows, costs


@pytest.mark.parametrize(
    "agent,arm",
    [
        ("anthropic", "naive"),
        ("mistral", "naive"),
        ("openai", "naive"),
        ("qwen", "naive"),
        ("openai", "optimised"),
        ("qwen", "optimised"),
    ],
)
def test_exp2_rowcount_macros_match_flat_data(agent, arm):
    """Ticket 0575: each \\ExpTwoRows*/Min/Max macro equals the median /
    min / max table-row count re-derived from the committed flat dirs."""
    rows, _ = _flat_rows_cost(agent, arm)
    assert rows, f"no report runs for {agent}/{arm}"
    macro_agent = {"anthropic": "Anthropic", "mistral": "Mistral", "openai": "OpenAI", "qwen": "Qwen"}[agent]
    macro_arm = {"naive": "Naive", "optimised": "Optimised"}[arm]
    med = statistics.median(rows)
    med_str = f"{med:.0f}" if float(med).is_integer() else f"{med:g}"
    assert _macro(f"ExpTwoRows{macro_agent}{macro_arm}") == med_str
    assert _macro(f"ExpTwoRowsMin{macro_agent}{macro_arm}") == str(min(rows))
    assert _macro(f"ExpTwoRowsMax{macro_agent}{macro_arm}") == str(max(rows))


@pytest.mark.parametrize("agent", ["openai"])
def test_exp2_cost_macros_match_flat_data(agent):
    """Ticket 0575: \\ExpTwoCost*Naive/Optimised equals the median per-run
    cost re-derived from the committed flat dirs (2-dp)."""
    macro_agent = {"openai": "OpenAI"}[agent]
    for arm, macro_arm in (("naive", "Naive"), ("optimised", "Optimised")):
        _, costs = _flat_rows_cost(agent, arm)
        assert costs, f"no costs for {agent}/{arm}"
        assert _macro(f"ExpTwoCost{macro_agent}{macro_arm}") == f"{statistics.median(costs):.2f}"


def test_exp2_no_handtyped_coverage_medians():
    """Ticket 0575: no hand-typed 'median NN rows' or 'median \\$N.NN' in the
    §exp2 coverage prose — they must flow through \\ExpTwoRows*/\\ExpTwoCost*
    macros (negative guard, 0557 polarity rule)."""
    sec = _exp2_section()
    bad_rows = re.findall(r"median\s+\d+\s+rows", sec)
    assert not bad_rows, f"hand-typed row-count median back in §exp2: {bad_rows}"
    bad_cost = re.findall(r"median\s+\\\$\d", sec)
    assert not bad_cost, f"hand-typed cost median back in §exp2: {bad_cost}"


def test_exp2_no_handtyped_f1_pairs():
    """Ticket 0572: §exp2 F1 value pairs flow from macros_exp2_f1.tex — a
    hand-typed '0.xx to 0.yy' pair in the UNexpanded source is a literal
    revert (negative guard per the 0557 polarity rule; the positive value
    checks live in test_manuscript_claims_alignment.py on expanded text)."""
    text = _unexpanded_body()
    start = text.find("\\label{sec:exp2}")
    assert start != -1, "no \\label{sec:exp2} in main.tex body"
    nxt = re.search(r"\\section\*?\{", text[start:])
    sec = text[start : start + nxt.start()] if nxt else text[start:]
    pairs = re.findall(r"0\.\d{2} to 0\.\d{2}", sec)
    assert not pairs, f"hand-typed F1 pairs back in §exp2: {pairs}"
