"""Tests for aedist.tabulate_comparaison — generate RAG comparison LaTeX table."""

import logging

from conftest import write_measurements

from aedist.tabulate_comparaison import (
    generate_comparaison_table,
    group_by_sweep,
    main,
)

# --- Fixtures ---

SAMPLE_METRICS = [
    # Census runs for gpt-5.4
    {
        "label": "sweep1_census/gpt-5.4-run1",
        "coverage": 0.491,
        "f1": 0.658,
    },
    {
        "label": "sweep1_census/gpt-5.4-run2",
        "coverage": 0.500,
        "f1": 0.660,
    },
    {
        "label": "sweep1_census/gpt-5.4-run3",
        "coverage": 0.470,
        "f1": 0.640,
    },
    # RAG runs for gpt-5.4
    {
        "label": "sweep_rag/gpt-5.4-run1",
        "coverage": 0.550,
        "f1": 0.720,
    },
    {
        "label": "sweep_rag/gpt-5.4-run2",
        "coverage": 0.560,
        "f1": 0.730,
    },
    {
        "label": "sweep_rag/gpt-5.4-run3",
        "coverage": 0.540,
        "f1": 0.710,
    },
    # Census runs for padme-qwen3.5-122b
    {
        "label": "sweep1_census/padme-qwen3.5-122b-run1",
        "coverage": 0.300,
        "f1": 0.436,
    },
    {
        "label": "sweep1_census/padme-qwen3.5-122b-run2",
        "coverage": 0.320,
        "f1": 0.465,
    },
    {
        "label": "sweep1_census/padme-qwen3.5-122b-run3",
        "coverage": 0.310,
        "f1": 0.450,
    },
    # RAG runs for padme-qwen3.5-122b
    {
        "label": "sweep_rag/padme-qwen3.5-122b-run1",
        "coverage": 0.280,
        "f1": 0.410,
    },
    {
        "label": "sweep_rag/padme-qwen3.5-122b-run2",
        "coverage": 0.290,
        "f1": 0.420,
    },
    {
        "label": "sweep_rag/padme-qwen3.5-122b-run3",
        "coverage": 0.270,
        "f1": 0.400,
    },
]


# --- group_by_sweep ---


def test_group_by_sweep_splits_census_and_rag():
    census, rag = group_by_sweep(SAMPLE_METRICS)
    assert "gpt-5.4" in census
    assert "padme-qwen3.5-122b" in census
    assert "gpt-5.4" in rag
    assert "padme-qwen3.5-122b" in rag


def test_group_by_sweep_census_count():
    census, _rag = group_by_sweep(SAMPLE_METRICS)
    assert len(census["gpt-5.4"]) == 3
    assert len(census["padme-qwen3.5-122b"]) == 3


def test_group_by_sweep_rag_count():
    _census, rag = group_by_sweep(SAMPLE_METRICS)
    assert len(rag["gpt-5.4"]) == 3
    assert len(rag["padme-qwen3.5-122b"]) == 3


def test_group_by_sweep_ignores_unknown_prefix():
    metrics = [{"label": "sweep3_other/gpt-5.4-run1", "coverage": 0.5, "f1": 0.6}]
    census, rag = group_by_sweep(metrics)
    assert len(census) == 0
    assert len(rag) == 0


# --- generate_comparaison_table: models in both sweeps ---


def test_generate_table_structure():
    latex, n = generate_comparaison_table(SAMPLE_METRICS)
    assert "\\begin{longtable}" in latex
    assert "\\end{longtable}" in latex
    assert "\\label{tab:comparaison}" in latex
    assert "\\caption{" in latex


def test_generate_table_model_count():
    _latex, n = generate_comparaison_table(SAMPLE_METRICS)
    assert n == 2


def test_generate_table_autogenerated_comment():
    latex, _ = generate_comparaison_table(SAMPLE_METRICS)
    assert latex.startswith("% Auto-generated")


def test_generate_table_header_columns():
    latex, _ = generate_comparaison_table(SAMPLE_METRICS)
    assert "F1 Base" in latex
    assert "F1 RAG" in latex
    assert "$\\Delta$F1" in latex


def test_generate_table_contains_model_names():
    latex, _ = generate_comparaison_table(SAMPLE_METRICS)
    assert "GPT-5.4" in latex
    assert "(L)" in latex  # padme model gets local marker


def test_generate_table_percentages():
    latex, _ = generate_comparaison_table(SAMPLE_METRICS)
    # GPT-5.4 census median F1 = 0.658 -> 65.8%
    assert "65.8" in latex
    # GPT-5.4 RAG median F1 = 0.720 -> 72.0%
    assert "72.0" in latex


def test_generate_table_sorted_by_f1_rag_desc():
    latex, _ = generate_comparaison_table(SAMPLE_METRICS)
    # GPT-5.4 RAG F1=0.720 > padme RAG F1=0.410, so GPT row comes first
    lines = latex.splitlines()
    data_lines = [
        l
        for l in lines
        if "\\\\" in l
        and "toprule" not in l
        and "midrule" not in l
        and "endhead" not in l
        and "bottomrule" not in l
        and "endlastfoot" not in l
        and "caption" not in l
        and "Model &" not in l
    ]
    gpt_line = next((i for i, l in enumerate(data_lines) if "GPT-5.4" in l), None)
    padme_line = next((i for i, l in enumerate(data_lines) if "(L)" in l), None)
    assert gpt_line is not None and padme_line is not None
    assert gpt_line < padme_line


# --- Models present in only one sweep are excluded ---


def test_only_one_sweep_excluded():
    """Models appearing in only one sweep should not appear in the table."""
    metrics = [
        # census only
        {"label": "sweep1_census/gpt-5.4-run1", "coverage": 0.5, "f1": 0.65},
        # rag only
        {"label": "sweep_rag/deepseek-v3.2-run1", "coverage": 0.4, "f1": 0.55},
    ]
    latex, n = generate_comparaison_table(metrics)
    assert n == 0
    assert "GPT-5.4" not in latex
    assert "DeepSeek" not in latex


# --- Delta sign formatting ---


def test_delta_positive_has_plus_sign():
    """Positive delta should show a '+' prefix."""
    latex, _ = generate_comparaison_table(SAMPLE_METRICS)
    # GPT-5.4: RAG F1 (0.720) - census F1 (0.658) = +0.062 -> +6.2%
    assert "+6.2" in latex


def test_delta_negative_no_plus_sign():
    """Negative delta should not have '+' prefix (just the minus from formatting)."""
    latex, _ = generate_comparaison_table(SAMPLE_METRICS)
    # padme: RAG F1 (0.410) - census F1 (0.450) = -0.040 -> -4.0%
    assert "-4.0" in latex
    # Ensure no "+−" combination for negative deltas
    assert "+-4.0" not in latex


def test_delta_zero_gets_plus_sign():
    """Zero delta should get '+' prefix (delta >= 0 path)."""
    metrics = [
        {"label": "sweep1_census/gpt-5.4-run1", "coverage": 0.5, "f1": 0.500},
        {"label": "sweep_rag/gpt-5.4-run1", "coverage": 0.5, "f1": 0.500},
    ]
    latex, _ = generate_comparaison_table(metrics)
    assert "+0.0" in latex


# --- Empty intersection produces warning and empty table ---


def test_empty_intersection_warning(caplog):
    """No common models should log a warning."""
    metrics = [
        {"label": "sweep1_census/gpt-5.4-run1", "coverage": 0.5, "f1": 0.65},
        {"label": "sweep_rag/deepseek-v3.2-run1", "coverage": 0.4, "f1": 0.55},
    ]
    with caplog.at_level(logging.WARNING):
        latex, n = generate_comparaison_table(metrics)
    assert n == 0
    assert "empty" in caplog.text.lower() or "no models" in caplog.text.lower()


def test_empty_intersection_no_data_rows():
    """Empty intersection should produce a table with no data rows."""
    metrics = [
        {"label": "sweep1_census/gpt-5.4-run1", "coverage": 0.5, "f1": 0.65},
    ]
    latex, n = generate_comparaison_table(metrics)
    assert n == 0
    assert "\\begin{longtable}" in latex
    assert "\\end{longtable}" in latex
    # No model name should appear
    assert "GPT-5.4" not in latex


# --- CLI integration ---


def test_main_writes_output(tmp_path):
    """main() reads measurements.jsonl and writes LaTeX output."""
    input_file = tmp_path / "measurements.jsonl"
    write_measurements(input_file, SAMPLE_METRICS)
    output_file = tmp_path / "tab_comparaison.tex"

    main(["--measurements", str(input_file), "--output", str(output_file)])

    content = output_file.read_text()
    assert "\\begin{longtable}" in content
    assert "\\label{tab:comparaison}" in content


def test_main_creates_parent_dirs(tmp_path):
    """main() creates parent directories if they don't exist."""
    input_file = tmp_path / "measurements.jsonl"
    write_measurements(input_file, SAMPLE_METRICS)
    output_file = tmp_path / "sub" / "dir" / "tab_comparaison.tex"

    main(["--measurements", str(input_file), "--output", str(output_file)])

    assert output_file.exists()
