"""No inline pgfplots in .tex files.

Figures must be generated by Python and included as PDF.
Inline \\begin{axis} blocks are banned repo-wide.
"""

import subprocess
from pathlib import Path

import pytest

pytestmark = pytest.mark.adherence

REPO_ROOT = Path(__file__).resolve().parent.parent


def _tracked_tex_files() -> list[Path]:
    result = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return [REPO_ROOT / f for f in result.stdout.split("\0") if f.endswith(".tex")]


@pytest.mark.xfail(reason="remediation pending: tickets 0131, 0132, 0133")
def test_no_begin_axis():
    violations = []
    for tex_file in _tracked_tex_files():
        for i, line in enumerate(tex_file.read_text().splitlines(), 1):
            if r"\begin{axis}" in line:
                violations.append(f"{tex_file.relative_to(REPO_ROOT)}:{i}")
    assert not violations, (
        f"{len(violations)} inline pgfplots chart(s) — "
        f"generate PDF with Python instead:\n" + "\n".join(f"  {v}" for v in violations)
    )
