"""Tests for aedist.tabulate_self_consistency — self-consistency LaTeX tables."""

import json

from aedist.tabulate_self_consistency import (
    generate_per_run_table,
    generate_self_consistency_table,
)

# --- Fixtures ---

SAMPLE_RESULTS = [
    {
        "model": "deepseek-v3.2",
        "n_runs": 3,
        "n_valid_runs": 3,
        "run_f1_scores": [0.3367, 0.6009, 0.6855],
        "run_n_matched": [33, 70, 85],
        "run_n_system": [33, 70, 85],
        "median_f1": 0.6009,
        "median_coverage": 0.4294,
        "median_precision": 1.0,
        "majority_f1": 0.386,
        "majority_coverage": 0.239,
        "majority_precision": 1.0,
        "majority_n_matched": 39,
        "majority_n_system": 39,
        "majority_n_hallucinated": 0,
        "n_majority_plants": 39,
        "union_f1": 0.955,
        "union_coverage": 0.914,
        "union_precision": 1.0,
        "union_n_matched": 149,
        "union_n_system": 149,
        "union_n_hallucinated": 0,
    },
    {
        "model": "gemini-2.5-flash-lite",
        "n_runs": 3,
        "n_valid_runs": 3,
        "run_f1_scores": [0.4045, 0.5801, 0.9674],
        "run_n_matched": [163, 163, 163],
        "run_n_system": [643, 399, 174],
        "median_f1": 0.5801,
        "median_coverage": 1.0,
        "median_precision": 0.408,
        "majority_f1": 0.81,
        "majority_coverage": 0.681,
        "majority_precision": 1.0,
        "majority_n_matched": 111,
        "majority_n_system": 111,
        "majority_n_hallucinated": 0,
        "n_majority_plants": 111,
        "union_f1": 0.324,
        "union_coverage": 1.0,
        "union_precision": 0.194,
        "union_n_matched": 163,
        "union_n_system": 843,
        "union_n_hallucinated": 680,
    },
]


# --- generate_self_consistency_table ---


def test_self_consistency_table_structure():
    latex = generate_self_consistency_table(SAMPLE_RESULTS)
    assert "\\begin{table}" in latex
    assert "\\end{table}" in latex
    assert "\\label{tab:self-consistency}" in latex


def test_self_consistency_table_header():
    latex = generate_self_consistency_table(SAMPLE_RESULTS)
    assert "Med.~F1" in latex
    assert "Maj.~F1" in latex
    assert "Union F1" in latex
    assert "Regime" in latex


def test_self_consistency_table_regime_detection():
    latex = generate_self_consistency_table(SAMPLE_RESULTS)
    # deepseek has 100% precision → truncation
    assert "truncation" in latex
    # gemini has 100% coverage → overgeneration
    assert "overgeneration" in latex


def test_self_consistency_table_sorted_by_median_f1():
    latex = generate_self_consistency_table(SAMPLE_RESULTS)
    lines = latex.splitlines()
    data_lines = [l for l in lines if "DeepSeek" in l or "Gemini" in l]
    # deepseek (60.1%) > gemini (58.0%) when sorted descending
    assert "DeepSeek" in data_lines[0]
    assert "Gemini" in data_lines[1]


def test_self_consistency_table_autogenerated_comment():
    latex = generate_self_consistency_table(SAMPLE_RESULTS)
    assert latex.startswith("% Auto-generated")


def test_self_consistency_table_best_delta_strategy():
    """Truncation models use union delta; overgeneration uses majority."""
    latex = generate_self_consistency_table(SAMPLE_RESULTS)
    lines = latex.splitlines()
    deepseek_line = [l for l in lines if "DeepSeek" in l][0]
    gemini_line = [l for l in lines if "Gemini" in l][0]
    # deepseek: union gain = 95.5 - 60.1 = +35.4%
    assert "+35.4" in deepseek_line
    # gemini: majority gain = 81.0 - 58.0 = +23.0%
    assert "+23.0" in gemini_line


# --- generate_per_run_table ---


def test_per_run_table_structure():
    latex = generate_per_run_table(SAMPLE_RESULTS)
    assert "\\begin{longtable}" in latex
    assert "\\end{longtable}" in latex
    assert "\\label{tab:per-run}" in latex


def test_per_run_table_shows_all_runs():
    latex = generate_per_run_table(SAMPLE_RESULTS)
    lines = latex.splitlines()
    # Each model has 3 data rows
    deepseek_rows = [l for l in lines if "33.7" in l or "60.1" in l or "68.5" in l]
    assert len(deepseek_rows) == 3


def test_per_run_table_gemini_hallucinations():
    """Gemini rows should show non-zero hallucination counts."""
    latex = generate_per_run_table(SAMPLE_RESULTS)
    lines = latex.splitlines()
    gemini_lines = [l for l in lines if "Gemini" in l or "100.0" in l]
    # At least one line should mention 480 hallucinated (643 - 163)
    assert any("480" in l for l in gemini_lines)


def test_per_run_table_truncation_zero_hallucinations():
    """Truncation-limited models have Plants == Matched (0 hallucinations)."""
    latex = generate_per_run_table(SAMPLE_RESULTS)
    lines = latex.splitlines()
    deepseek_rows = [l for l in lines if "33.7" in l or "60.1" in l or "68.5" in l]
    # Each row has "& 0 &" for hallucinations
    for row in deepseek_rows:
        parts = row.split("&")
        # Halluc column is the 5th field (index 4)
        halluc = parts[4].strip().rstrip("\\").strip()
        assert halluc == "0", f"Expected 0 hallucinations, got {halluc!r} in {row}"


# --- CLI integration ---


def test_main_writes_outputs(tmp_path):
    """main() reads input JSON and writes both LaTeX outputs."""
    from aedist.tabulate_self_consistency import main

    input_file = tmp_path / "summary.json"
    input_file.write_text(json.dumps(SAMPLE_RESULTS))
    output_file = tmp_path / "tab_sc.tex"
    per_run_file = tmp_path / "tab_pr.tex"

    main(
        [
            "--input",
            str(input_file),
            "--output",
            str(output_file),
            "--per-run-output",
            str(per_run_file),
        ]
    )

    assert output_file.exists()
    assert per_run_file.exists()
    assert "\\label{tab:self-consistency}" in output_file.read_text()
    assert "\\label{tab:per-run}" in per_run_file.read_text()
