"""Mandate symbolic cross-references in slides/manuscript/main.tex.

Ticket 0518 introduced symbolic cross-references; ticket 0524 converted the
manuscript to hand-curated LaTeX. Every section/figure/table number is
generated by the typesetter. Two invariants follow:

1. *No hand-typed reference literal in prose.* A bare ``§3`` / ``Figure 4`` /
   ``Figure S1`` / ``Annex C`` / ``Table 1`` in the body would silently rot
   under restructuring. References must be symbolic: ``§\\ref{sec:…}`` /
   ``Figure~\\ref{fig:…}`` / ``Table~\\ref{tbl:…}`` (or ``\\Cref``), with the
   annex lettering supplied by ``\\appendix`` through bare ``\\ref``.

2. *Every symbolic reference resolves.* Each ``\\ref``/``\\Cref``/``\\cref``
   to a ``sec:``/``fig:``/``tbl:`` id must point at a ``\\label`` defined in
   the document. No orphan refs.

``\\texttt{…}`` spans are prose here and are scanned too — a filename literal
contains no ``Figure N`` token, so this is safe and keeps the scan simple.
"""

import re
from pathlib import Path

import pytest
from manuscript_source import body, body_raw, normalized

pytestmark = pytest.mark.adherence

REPORT = Path(__file__).resolve().parent.parent / "report" / "report.tex"

# Hand-typed reference literals that must NOT appear in prose. The symbolic
# forms ("§\ref{…}", "Figure~\ref{…}") put a backslash, not a digit, after the
# prefix token, so they do not match.
HANDTYPED_RES = [
    (re.compile(r"§\s*\d"), "§N section reference"),
    (re.compile(r"\bFigure\s+S?\d"), "Figure N / Figure SN reference"),
    (re.compile(r"\bAnnex\s+[A-G]\b"), "Annex X reference"),
    (re.compile(r"\bTable\s+\d"), "Table N reference"),
]

LABEL_RE = re.compile(r"\\label\{((?:sec|fig|tbl):[a-z0-9-]+)\}")
REF_RE = re.compile(r"\\[Cc]?ref\{((?:sec|fig|tbl):[a-z0-9-]+)\}")


def test_no_hand_typed_references_in_prose() -> None:
    """No literal §N / Figure N / Annex X / Table N in the document body."""
    prose = body()
    violations = []
    for rx, label in HANDTYPED_RES:
        for m in rx.finditer(prose):
            ctx = prose[max(0, m.start() - 40) : m.end() + 40]
            violations.append(f"{label}: …{ctx}…")
    assert not violations, (
        f"{len(violations)} hand-typed cross-reference literal(s) — use "
        "§\\ref{sec:…} / Figure~\\ref{fig:…} / Table~\\ref{tbl:…} "
        "(tickets 0518/0524):\n" + "\n".join(f"  {v}" for v in violations)
    )


def test_every_reference_resolves_to_a_defined_label() -> None:
    """Each \\ref/\\Cref to sec:/fig:/tbl: points at a defined \\label."""
    text = body_raw()
    defined = set(LABEL_RE.findall(text))
    referenced = set(REF_RE.findall(text))
    orphans = sorted(referenced - defined)
    assert not orphans, (
        f"{len(orphans)} symbolic reference(s) with no matching \\label "
        f"definition: {orphans}\n  defined labels: {sorted(defined)}"
    )


def test_at_least_one_symbolic_reference_of_each_kind() -> None:
    """Guard against a regex that passes vacuously: the migration is real.

    The manuscript must actually use section, figure, and table references in
    symbolic form — otherwise test_no_hand_typed_references_in_prose could pass
    on a document that simply deleted every cross-reference.
    """
    referenced = set(REF_RE.findall(body_raw()))
    for prefix in ("sec:", "fig:", "tbl:"):
        assert any(r.startswith(prefix) for r in referenced), (
            f"no symbolic {prefix} reference found — migration incomplete"
        )


# --- report/report.tex (FR prose) — ticket 0536 ------------------------------
#
# PR #959 hardcoded « pages 1--2 / page 3 » in a report.tex caption; caught
# only in review. Same invariant as above, French patterns: numbers come from
# the typesetter (\ref, \pageref, counters), never typed into prose. The
# symbolic forms put a backslash after the prefix token, so they do not match.
HANDTYPED_FR_RES = [
    (re.compile(r"§\s*\d"), "§N section reference"),
    (re.compile(r"\bFigures?\s+S?\d"), "Figure N reference"),
    (re.compile(r"\bTableaux?\s+\d"), "Tableau N reference"),
    (re.compile(r"\bAnnexes?\s+[A-G]\b"), "Annexe X reference"),
    (re.compile(r"\bpages?\s+\d"), "page N reference"),
]

# Tiny whitelist for false positives (verbatim numbers, bibliography…).
# Entries are exact substrings of the normalized prose; keep this list short.
REPORT_CROSSREF_WHITELIST: list[str] = []


def report_prose() -> str:
    """Normalized prose of report/report.tex (comments dropped)."""
    if not REPORT.exists():
        pytest.skip("report/report.tex not found")
    return normalized(REPORT.read_text(encoding="utf-8"))


def test_no_hand_typed_references_in_report_prose() -> None:
    """No literal §N / Figure N / Tableau N / Annexe X / page N in report.tex."""
    prose = report_prose()
    violations = []
    for rx, label in HANDTYPED_FR_RES:
        for m in rx.finditer(prose):
            ctx = prose[max(0, m.start() - 40) : m.end() + 40]
            if any(w in ctx for w in REPORT_CROSSREF_WHITELIST):
                continue
            violations.append(f"{label}: …{ctx}…")
    assert not violations, (
        f"{len(violations)} hand-typed cross-reference literal(s) in "
        "report/report.tex — use \\ref{…}/\\pageref{…} or layout-stable "
        "phrasing (ticket 0536):\n" + "\n".join(f"  {v}" for v in violations)
    )
