"""Tests for aedist.tabulate_variance — ANOVA table in LaTeX."""

from aedist.tabulate_variance import generate_variance_table

SAMPLE_ANOVA = {
    "eta_sq_model": 0.45,
    "eta_sq_method": 0.38,
    "eta_sq_interaction": 0.12,
    "eta_sq_residual": 0.05,
    "omega_sq_model": 0.42,
    "omega_sq_method": 0.35,
    "omega_sq_interaction": 0.10,
    "anova": {
        "ss_a": 1.234,
        "ss_b": 0.987,
        "ss_ab": 0.321,
        "ss_resid": 0.123,
        "ss_total": 2.665,
        "df_a": 4,
        "df_b": 3,
        "df_ab": 12,
        "df_resid": 40,
        "df_total": 59,
        "f_a": 10.05,
        "f_b": 8.02,
        "f_ab": 2.61,
        "p_a": 0.001,
        "p_b": 0.003,
        "p_ab": 0.045,
    },
}


def test_table_has_longtable_env():
    """Output uses longtable environment."""
    latex = generate_variance_table(SAMPLE_ANOVA)
    assert "\\begin{longtable}" in latex
    assert "\\end{longtable}" in latex


def test_table_has_label():
    """Table has the expected label."""
    latex = generate_variance_table(SAMPLE_ANOVA)
    assert "\\label{tab:variance}" in latex


def _variance_data_rows(latex):
    """Extract data rows from the variance longtable."""
    rows = []
    in_data = False
    for line in latex.splitlines():
        stripped = line.strip()
        if r"\endhead" in stripped:
            in_data = True
            continue
        if r"\midrule" in stripped and in_data:
            continue
        if r"\end{longtable}" in stripped:
            break
        if in_data and "&" in stripped:
            cells = [c.strip().rstrip("\\").strip() for c in stripped.split("&")]
            rows.append(cells)
    return rows


def test_table_has_all_sources():
    """All four variance sources appear as rows with correct values."""
    latex = generate_variance_table(SAMPLE_ANOVA)
    rows = _variance_data_rows(latex)
    sources = [r[0] for r in rows]
    assert "Model" in sources
    assert "Method" in sources
    assert "Residual" in sources
    # Verify Model row has correct SS and F values
    model_row = rows[sources.index("Model")]
    assert model_row[1] == "1.2340"  # SS
    assert model_row[2] == "4"  # df
    assert model_row[3] == "10.05"  # F


def test_table_has_eta_squared():
    """Eta-squared values appear in the table."""
    latex = generate_variance_table(SAMPLE_ANOVA)
    assert "0.45" in latex  # eta_sq_model
    assert "0.38" in latex  # eta_sq_method


def test_table_has_df():
    """Degrees of freedom appear in the table."""
    latex = generate_variance_table(SAMPLE_ANOVA)
    # df_a = 4, df_b = 3, df_ab = 12, df_resid = 40
    assert "4" in latex
    assert "3" in latex


def test_table_has_f_statistics():
    """F-statistics appear in the table."""
    latex = generate_variance_table(SAMPLE_ANOVA)
    assert "10.05" in latex
    assert "8.02" in latex


def test_table_has_p_values():
    """p-values in correct cells for each source row."""
    latex = generate_variance_table(SAMPLE_ANOVA)
    rows = _variance_data_rows(latex)
    sources = [r[0] for r in rows]
    model_row = rows[sources.index("Model")]
    method_row = rows[sources.index("Method")]
    assert model_row[4] == "0.001"  # p_a
    assert method_row[4] == "0.003"  # p_b


def test_table_has_omega_squared():
    """Omega-squared values appear in the table."""
    latex = generate_variance_table(SAMPLE_ANOVA)
    assert "omega" in latex or "\\omega" in latex
    assert "0.42" in latex


def test_autogenerated_comment():
    """Table starts with auto-generated comment."""
    latex = generate_variance_table(SAMPLE_ANOVA)
    assert latex.startswith("% Auto-generated")
