"""Tests for aedist.tabulate_variance — ANOVA table in LaTeX."""

import json

import pytest

from aedist.tabulate_variance import _fmt_p, generate_variance_table, main

SAMPLE_ANOVA = {
    "eta_sq_model": 0.45,
    "eta_sq_method": 0.38,
    "eta_sq_interaction": 0.12,
    "eta_sq_residual": 0.05,
    "omega_sq_model": 0.42,
    "omega_sq_method": 0.35,
    "omega_sq_interaction": 0.10,
    "anova": {
        "ss_a": 1.234,
        "ss_b": 0.987,
        "ss_ab": 0.321,
        "ss_resid": 0.123,
        "ss_total": 2.665,
        "df_a": 4,
        "df_b": 3,
        "df_ab": 12,
        "df_resid": 40,
        "df_total": 59,
        "f_a": 10.05,
        "f_b": 8.02,
        "f_ab": 2.61,
        "p_a": 0.001,
        "p_b": 0.003,
        "p_ab": 0.045,
    },
}


def test_table_has_longtable_env():
    """Output uses longtable environment."""
    latex = generate_variance_table(SAMPLE_ANOVA)
    assert "\\begin{longtable}" in latex
    assert "\\end{longtable}" in latex


def test_table_has_label():
    """Table has the expected label."""
    latex = generate_variance_table(SAMPLE_ANOVA)
    assert "\\label{tab:variance}" in latex


def test_table_has_all_sources():
    """All four variance sources appear in the table."""
    latex = generate_variance_table(SAMPLE_ANOVA)
    assert "Model" in latex
    assert "Method" in latex
    assert "Interaction" in latex or "Model $\\times$ Method" in latex
    assert "Residual" in latex


def test_table_has_eta_squared():
    """Eta-squared values appear in the table."""
    latex = generate_variance_table(SAMPLE_ANOVA)
    assert "0.45" in latex  # eta_sq_model
    assert "0.38" in latex  # eta_sq_method


def test_table_has_df():
    """Degrees of freedom appear in the table."""
    latex = generate_variance_table(SAMPLE_ANOVA)
    # df_a = 4, df_b = 3, df_ab = 12, df_resid = 40
    assert "4" in latex
    assert "3" in latex


def test_table_has_f_statistics():
    """F-statistics appear in the table."""
    latex = generate_variance_table(SAMPLE_ANOVA)
    assert "10.05" in latex
    assert "8.02" in latex


def test_table_has_p_values():
    """p-values appear in the table."""
    latex = generate_variance_table(SAMPLE_ANOVA)
    assert "$<$0.001" in latex or "0.001" in latex


def test_table_has_omega_squared():
    """Omega-squared values appear in the table."""
    latex = generate_variance_table(SAMPLE_ANOVA)
    assert "omega" in latex or "\\omega" in latex
    assert "0.42" in latex


def test_autogenerated_comment():
    """Table starts with auto-generated comment."""
    latex = generate_variance_table(SAMPLE_ANOVA)
    assert latex.startswith("% Auto-generated")


# --- _fmt_p ---


class TestFmtP:
    """Tests for _fmt_p() p-value formatter."""

    def test_none_returns_dashes(self):
        assert _fmt_p(None) == "---"

    def test_very_small_p(self):
        assert _fmt_p(0.0001) == "$<$0.001"
        assert _fmt_p(0.0009) == "$<$0.001"

    def test_small_p_three_decimals(self):
        result = _fmt_p(0.005)
        assert result == "0.005"

    def test_moderate_p_two_decimals(self):
        result = _fmt_p(0.045)
        assert result == "0.04" or result == "0.05"  # rounding
        # More precisely:
        assert _fmt_p(0.05) == "0.05"
        assert _fmt_p(0.10) == "0.10"

    def test_boundary_at_0_001(self):
        # p = 0.001 is NOT < 0.001, so it should go to the 3-decimal branch
        result = _fmt_p(0.001)
        assert result == "0.001"

    def test_boundary_at_0_01(self):
        # p = 0.01 is NOT < 0.01, so it should go to the 2-decimal branch
        result = _fmt_p(0.01)
        assert result == "0.01"

    def test_large_p(self):
        assert _fmt_p(0.95) == "0.95"
        assert _fmt_p(1.0) == "1.00"


# --- main (CLI) ---


class TestMainCLI:
    """Tests for main() CLI entry point."""

    def test_main_reads_json_writes_latex(self, tmp_path):
        input_file = tmp_path / "decomposition.json"
        input_file.write_text(json.dumps(SAMPLE_ANOVA))

        output_file = tmp_path / "table.tex"

        main(["--input", str(input_file), "--output", str(output_file)])

        assert output_file.exists()
        content = output_file.read_text()
        assert "\\begin{longtable}" in content
        assert "\\end{longtable}" in content
        assert "% Auto-generated" in content

    def test_main_creates_output_parents(self, tmp_path):
        input_file = tmp_path / "decomposition.json"
        input_file.write_text(json.dumps(SAMPLE_ANOVA))

        output_file = tmp_path / "deep" / "nested" / "table.tex"

        main(["--input", str(input_file), "--output", str(output_file)])

        assert output_file.exists()

    def test_main_output_contains_data(self, tmp_path):
        input_file = tmp_path / "decomposition.json"
        input_file.write_text(json.dumps(SAMPLE_ANOVA))

        output_file = tmp_path / "table.tex"

        main(["--input", str(input_file), "--output", str(output_file)])

        content = output_file.read_text()
        # Check ANOVA values appear in the output
        assert "0.45" in content  # eta_sq_model
        assert "10.05" in content  # f_a
        assert "\\label{tab:variance}" in content
