"""Convert experiment results to LaTeX tables and macros.

Usage:
    python -m aedist.convert --output report/inputs/generated/
    python -m aedist.convert --output report/inputs/generated/ \\
        --metrics experiments/results/sweep1_census/all_metrics.json

Generates:
    macros.tex         - \newcommand definitions for inline numbers
    tab_relances.tex   - Table: LLM results with follow-up prompts
    tab_comparaison.tex - Table: with vs without source documents
"""

import argparse
import json
import logging
import re
from pathlib import Path

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Metrics loading
# ---------------------------------------------------------------------------

def load_metrics(metrics_path: Path) -> dict[str, dict]:
    """Load all_metrics.json and return best-run metrics per model.

    The file contains one entry per model/run with labels like
    ``sweep1_census/claude-3.5-sonnet-run1``.  We group by model slug
    (stripping ``-runN``) and keep the run with the highest F1 score.

    Returns ``{model_slug: metrics_dict}``.
    """
    if not metrics_path.exists():
        log.warning("Metrics file not found: %s", metrics_path)
        return {}

    with open(metrics_path) as fh:
        raw = json.load(fh)

    best: dict[str, dict] = {}
    for entry in raw:
        label = entry.get("label", "")
        # label format: "sweep1_census/model-slug-runN"
        name = label.rsplit("/", 1)[-1]
        slug = re.sub(r"-run\d+$", "", name)
        if slug not in best or entry.get("f1", 0) > best[slug].get("f1", 0):
            best[slug] = entry
    return best


# ---------------------------------------------------------------------------
# Macros generation
# ---------------------------------------------------------------------------

# Fallback values (used when metrics aren't available).
# Keys are LaTeX macro names used in the report.
MACRO_FALLBACKS = {
    "SimplyAskDeepSeek": 64,
    "SimplyAskGeminiFlash": 41,
    "SimplyAskClaudeSonnet": 38,
    "SimplyAskGPTFourO": 33,
    "SimplyAskPerplexityPro": 22,
    "SimplyAskLlama": 18,
}


def _slug_to_macro(slug: str) -> str:
    """Convert a model slug to a LaTeX-safe macro name.

    ``claude-sonnet-4.6`` → ``SimplyAskClaudeSonnet46``
    """
    parts = slug.replace(".", "").replace(":", "").split("-")
    return "SimplyAsk" + "".join(p.capitalize() for p in parts)


def generate_macros(metrics: dict[str, dict]) -> str:
    r"""Generate LaTeX ``\newcommand`` definitions for inline numbers.

    When *metrics* are available, one macro per model is emitted using
    ``n_matched`` as the value.  Fallback macros are always included for
    backward compatibility with existing LaTeX sources.
    """
    values = dict(MACRO_FALLBACKS)

    for slug, m in metrics.items():
        if "n_matched" in m:
            values[_slug_to_macro(slug)] = m["n_matched"]

    lines = [
        "% Auto-generated by src/convert.py — do not edit",
        "% Experiment 1: Simply ask",
    ]
    for name, value in sorted(values.items()):
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Table: tab_relances
# ---------------------------------------------------------------------------

# Hardcoded data from report lines 244-250.
# Columns: label, prompt1, relance1, relance2, relance3, relance4
# As experiments are automated, prompt1 becomes data-driven (Exp 1),
# relance columns become data-driven (Exp 2).
TAB_RELANCES_DATA = [
    ("Claude 3.5 Sonnet", "34", "24", "50", "73", "+14 = 87"),
    ("DeepSeek (COT off, Search off)", "10", "24", "48", "70", "80"),
    ("GPT-4o (on Poe)", "25", "36", "50", "60+", "70+"),
    ("Llama 3.3 70B (on Poe)", "32", "18", "44", "bloque", "n/a"),
    ("Qwen 2.5 72B T (on Poe)", "19", "36", "bloque", "", ""),
    ("o3-mini (medium)", "12", "7", "14", "25", "=c'est possible"),
    ("o3-mini (high)", "15", "8", "19", "25", "=Potentially"),
]


def generate_tab_relances(metrics: dict[str, dict]) -> str:
    """Generate the tab:relances longtable."""
    rows = []
    for label, p1, r1, r2, r3, r4 in TAB_RELANCES_DATA:
        # TODO: override p1 from metrics when Experiment 1 is re-run
        # TODO: override r1-r4 from exp2_results when Experiment 2 is automated
        rows.append(f"{label} & {p1} & {r1} & {r2} & {r3} & {r4} \\\\")

    return (
        "% Auto-generated by src/convert.py — do not edit\n"
        "\\begin{longtable}[]{@{}llllll@{}}\n"
        "\\caption{Évolution du nombre de centrales thermiques identifiées "
        "par les modèles de langage après relances "
        "successives.}\\label{tab:relances}\\\\\n"
        "\\toprule\\noalign{}\n"
        "Modèle & Prompt 1 & Relance 1 & Relance 2 & Relance 3 & Relance 4 \\\\\n"
        "\\midrule\\noalign{}\n"
        "\\endhead\n"
        "\\bottomrule\\noalign{}\n"
        "\\endlastfoot\n"
        + "\n".join(rows) + "\n"
        "\\end{longtable}\n"
    )


# ---------------------------------------------------------------------------
# Table: tab_comparaison
# ---------------------------------------------------------------------------

# Hardcoded data from report lines 530-557.
# As experiments are automated, "sans" becomes data-driven (Exp 1),
# "avec" becomes data-driven (Exp 3 / RAG).
TAB_COMPARAISON_DATA = [
    ("Claude 3.5 Sonnet", "63", "\\tnote{a,b}"),
    ("DeepSeek-R1 (on Poe)", "40", "65"),
    ("GPT-4o (on Poe)", "\\tnote{c,cc} puis 33", "49"),
    ("o1-mini (on Poe)", "37\\tnote{c,e}", "39\\tnote{c,f}"),
    ("o3-mini medium", "32\\tnote{g}", "41"),
    ("o3-mini high", "39\\tnote{g}", "78"),
]

TAB_COMPARAISON_NOTES = [
    ("a", "Liste les Units et non les Plants."),
    ("b", "Stoppé par limite."),
    ("c", "Liste l'hydroélectricité."),
    ("cc", "La relance est «~Thermal power is coal, gas and oil~»."),
    ("d", "Stoppé limite RPD."),
    ("e", "Includes a nonsense line at the end about thermal renewable."),
    ("f", "Se limite aux projets opérationnels."),
    ("g", "Source himself instead of from the provided docs."),
]


def generate_tab_comparaison(metrics: dict[str, dict]) -> str:
    """Generate the tab:comparaison ThreePartTable."""
    notes = "\n".join(
        f"\\item[{key}] {text}" for key, text in TAB_COMPARAISON_NOTES
    )
    rows = []
    for label, sans, avec in TAB_COMPARAISON_DATA:
        # TODO: override sans from metrics when Experiment 1 is re-run
        # TODO: override avec from exp3_results when Experiment 3 is automated
        rows.append(f"{label} & {sans} & {avec} \\\\")

    return (
        "% Auto-generated by src/convert.py — do not edit\n"
        "\\begin{ThreePartTable}\n"
        "\\begin{TableNotes}[flushleft]\\footnotesize\n"
        + notes + "\n"
        "\\end{TableNotes}\n"
        "\\begin{longtable}[]{@{}lll@{}}\n"
        "\\caption{Comparaison du nombre de centrales thermiques vietnamiennes "
        "identifiées par différents modèles, avec et sans documents sources, "
        "janvier-février 2025}\\label{tab:comparaison}\\\\\n"
        "\\toprule\n"
        "Modèle & Sans documents & Avec documents \\\\\n"
        "\\midrule\n"
        "\\endhead\n"
        "\\bottomrule\n"
        "\\insertTableNotes\\\\\n"
        "\\endlastfoot\n"
        + "\n".join(rows) + "\n"
        "\\end{longtable}\n"
        "\\end{ThreePartTable}\n"
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser(
        description="Convert experiment results to LaTeX"
    )
    parser.add_argument("--output", required=True, help="Output directory")
    parser.add_argument(
        "--metrics",
        help="Path to all_metrics.json (from sweep1-summary)",
    )
    args = parser.parse_args()

    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Load metrics from flat JSON structure
    if args.metrics:
        metrics = load_metrics(Path(args.metrics))
    else:
        metrics = {}

    if not metrics:
        log.info("No metrics loaded — using fallback values")

    # Generate macros
    macros_path = output_dir / "macros.tex"
    macros_path.write_text(generate_macros(metrics))
    log.info("Wrote %s", macros_path)

    # Generate tables
    tab_path = output_dir / "tab_relances.tex"
    tab_path.write_text(generate_tab_relances(metrics))
    log.info("Wrote %s", tab_path)

    tab_path = output_dir / "tab_comparaison.tex"
    tab_path.write_text(generate_tab_comparaison(metrics))
    log.info("Wrote %s", tab_path)


if __name__ == "__main__":
    main()
