"""Generate Experiment 1 cost summary LaTeX table from measurements.jsonl.

Pipeline phase: P3 (analyze & render) — invoked by experiments/render.mk.

Per-model totals for the parametric baseline sweep
(``experiments/archive/outputs/exp1/baseline/``): how many reps succeeded,
how many refused, how many tokens in / out the sweep cost, and total
wall time. Plus a TOTAL row.

Usage:
    python -m aedist.tabulate_exp1_cost_summary \\
        --measurements measurements.jsonl \\
        --output report/inputs/generated/tab_exp1_cost_summary.tex

Sources rows whose ``result_file`` starts with
``experiments/archive/outputs/exp1/baseline/`` (excluding ``baseline.pilot/``).
"""

import argparse
import json
import logging
import statistics
from pathlib import Path

from .tabulate_utils import format_model_name

log = logging.getLogger(__name__)

P1_BASE_PATH_PREFIX = "experiments/archive/outputs/exp1/baseline/"
P1_PILOT_MARKER = "/baseline.pilot/"


def _is_p1_base_row(result_file: str) -> bool:
    return (
        isinstance(result_file, str)
        and result_file.startswith(P1_BASE_PATH_PREFIX)
        and P1_PILOT_MARKER not in result_file
    )


def aggregate_per_model(records: list[dict]) -> list[dict]:
    """Group p1_base records by model and compute per-model totals."""
    by_model: dict[str, dict] = {}
    for rec in records:
        rf = rec.get("result_file", "")
        if not _is_p1_base_row(rf):
            continue
        mp = rec.get("method_params") or {}
        if isinstance(mp, str):
            continue
        model = mp.get("model")
        if not model:
            continue
        ru = rec.get("resource_use") or {}
        rs = rec.get("result_summary") or {}
        status = rs.get("status", "unknown")
        agg = by_model.setdefault(
            model,
            {
                "model": model,
                "n_ok": 0,
                "n_refused": 0,
                "n_other": 0,
                "tokens_in_total": 0,
                "tokens_out_total": 0,
                "cost_usd_total": 0.0,
                "wall_s_values": [],
            },
        )
        if status == "ok":
            agg["n_ok"] += 1
        elif status == "refusal":
            agg["n_refused"] += 1
        else:
            agg["n_other"] += 1
        agg["tokens_in_total"] += int(ru.get("tokens_in") or 0)
        agg["tokens_out_total"] += int(ru.get("tokens_out") or 0)
        agg["cost_usd_total"] += float(ru.get("cost_usd") or 0.0)
        agg["wall_s_values"].append(float(ru.get("wall_s") or 0.0))
    for agg in by_model.values():
        wall_values = agg.pop("wall_s_values")
        agg["median_wall_s"] = statistics.median(wall_values) if wall_values else 0.0
    return sorted(by_model.values(), key=lambda r: r["model"])


def generate_table_tex(rows: list[dict]) -> str:
    lines = [
        "% Auto-generated by aedist.tabulate_exp1_cost_summary — do not edit",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\caption{Experiment 1 cost summary: per-model totals across 5 reps of the parametric baseline, with median wall time. ``declined'' covers responses where the model refused the task (refusal-opener language). ``error'' covers genuine extraction failures.}\\label{tab:exp1-cost-summary}",
        "\\begin{tabular}{@{}lrrrrrrr@{}}",
        "\\toprule",
        "Model & ok & declined & error & tokens in & tokens out & cost (USD) & wall (s) \\\\",
        "\\midrule",
    ]
    total = {
        "n_ok": 0,
        "n_refused": 0,
        "n_other": 0,
        "tokens_in_total": 0,
        "tokens_out_total": 0,
        "cost_usd_total": 0.0,
    }
    for r in rows:
        name = format_model_name(r["model"])
        lines.append(
            f"{name} & {r['n_ok']} & {r['n_refused']} & {r['n_other']} & "
            f"{r['tokens_in_total']:,} & {r['tokens_out_total']:,} & "
            f"\\${r['cost_usd_total']:.4f} & {r['median_wall_s']:.1f} \\\\"
        )
        for k in total:
            total[k] += r[k]
    lines.extend(
        [
            "\\midrule",
            f"\\textbf{{Total}} & {total['n_ok']} & {total['n_refused']} & "
            f"{total['n_other']} & {total['tokens_in_total']:,} & "
            f"{total['tokens_out_total']:,} & \\${total['cost_usd_total']:.4f} & --- \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
        ]
    )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--measurements",
        type=Path,
        default=Path("measurements.jsonl"),
        help="Path to measurements.jsonl (default: cwd/measurements.jsonl).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="LaTeX output file (e.g. report/inputs/generated/tab_exp1_cost_summary.tex).",
    )
    args = parser.parse_args(argv)

    if not args.measurements.exists():
        raise SystemExit(f"measurements file not found: {args.measurements}")

    records = []
    with args.measurements.open() as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            records.append(json.loads(line))

    rows = aggregate_per_model(records)
    if not rows:
        raise SystemExit("No p1_base rows found in measurements.jsonl.")

    table = generate_table_tex(rows)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(table, encoding="utf-8")
    log.info(
        "Wrote %s (%d models, %d rows)",
        args.output,
        len(rows),
        sum(r["n_ok"] + r["n_refused"] + r["n_other"] for r in rows),
    )


if __name__ == "__main__":
    main()
