"""Generate LaTeX \\newcommand macros from measurements.jsonl.

Pipeline phase: P3 (analyze & render) — invoked by experiments/render.mk.

Reads per-run metrics, groups by model slug (stripping -runN suffix
and directory prefix), computes median F1, and emits macros for
the report preamble.

Usage:
    uv run python -m aedist.tabulate_macros \\
        --measurements measurements.jsonl \\
        --output report/inputs/generated/macros.tex
"""

import argparse
import logging
import statistics
from pathlib import Path

from .stats import bootstrap_ci
from .tabulate_utils import strip_label as slug_from_label
from .tabulate_utils import titlecase_slug

log = logging.getLogger(__name__)


def load_and_summarize(metrics: list[dict]) -> dict[str, dict]:
    """Group metrics by model slug and compute median F1.

    Returns dict mapping slug -> {median_f1, is_local, runs, f1_values}.
    """
    by_model: dict[str, list[float]] = {}
    for entry in metrics:
        slug = slug_from_label(entry["label"])
        by_model.setdefault(slug, []).append(entry["f1"])

    summary = {}
    for slug, f1_values in by_model.items():
        summary[slug] = {
            "median_f1": round(statistics.median(f1_values), 4),
            "is_local": slug.startswith("padme-"),
            "runs": len(f1_values),
            "f1_values": f1_values,
        }
    return summary


def _prettify(slug: str) -> str:
    """Prettify a model slug for LaTeX display."""
    return slug.replace("-", " ").replace("_", " ").title()


def _headline_pretty(slug: str) -> str:
    """Prettify a model slug using brand-aware titlecase (e.g. DeepSeek V3.2)."""
    return titlecase_slug(slug).replace("-", " ")


def load_headline_result(
    metrics: list[dict],
    model_slug: str = "deepseek-v3.2",
    method: str = "rag_per_fuel",
) -> dict:
    """Filter metrics to the headline model/method and compute mean + bootstrap CI.

    Rows are matched when their label starts with ``"{method}/"`` (exact first
    path segment) and the slug extracted from the label contains ``model_slug``
    as a substring. This deliberately excludes ``rag_per_fuel_v2/`` etc. when
    ``method="rag_per_fuel"`` (post-0120: formerly ``decomposed``).

    Returns a dict with keys:
        f1_values   -- list of matched F1 scores
        mean        -- arithmetic mean
        ci_lo       -- lower 95% bootstrap CI bound
        ci_hi       -- upper 95% bootstrap CI bound
        n_runs      -- number of matched rows
    """
    prefix = f"{method}/"
    f1_values = [
        entry["f1"]
        for entry in metrics
        if entry["label"].startswith(prefix) and model_slug in slug_from_label(entry["label"])
    ]
    if not f1_values:
        return {"f1_values": [], "mean": 0.0, "ci_lo": 0.0, "ci_hi": 0.0, "n_runs": 0}
    mean, ci_lo, ci_hi = bootstrap_ci(f1_values, seed=42)
    return {
        "f1_values": f1_values,
        "mean": mean,
        "ci_lo": ci_lo,
        "ci_hi": ci_hi,
        "n_runs": len(f1_values),
    }


def generate_macros(
    summary: dict[str, dict],
    headline_model: str = "deepseek-v3.2",
    headline_method: str = "rag_per_fuel",
    headline_metrics: list[dict] | None = None,
) -> str:
    """Generate LaTeX \\newcommand definitions from model summary.

    headline_metrics, if provided, is the raw metrics list used to compute
    the \\Headline* macros.  When omitted the headline macros fall back to
    zeros (safe for census-only invocations that don't have raw run data).
    """
    num_models = len(summary)
    local_models = {s: v for s, v in summary.items() if v["is_local"]}
    cloud_models = {s: v for s, v in summary.items() if not v["is_local"]}

    # Best overall
    best_slug = max(summary, key=lambda s: summary[s]["median_f1"])
    best_f1 = summary[best_slug]["median_f1"]

    # Best local (padme- prefix)
    if local_models:
        best_local_slug = max(local_models, key=lambda s: local_models[s]["median_f1"])
        best_local_f1 = local_models[best_local_slug]["median_f1"]
    else:
        best_local_slug = "none"
        best_local_f1 = 0.0

    # Plant range (based on 163 reference plants)
    ref_plants = 163
    f1_values = [v["median_f1"] for v in summary.values()]
    min_plants = round(min(f1_values) * ref_plants)
    max_plants = round(max(f1_values) * ref_plants)

    # Bootstrap CI for best model (if raw values available)
    best_vals = summary[best_slug].get("f1_values", [])
    if len(best_vals) > 1:
        _, ci_lo, ci_hi = bootstrap_ci(best_vals, seed=42)
        best_ci_str = f"{ci_lo * 100:.1f}, {ci_hi * 100:.1f}"
    else:
        best_ci_str = f"{best_f1 * 100:.1f}, {best_f1 * 100:.1f}"

    # Headline-pinned macros (Option A)
    if headline_metrics is not None:
        hr = load_headline_result(headline_metrics, headline_model, headline_method)
    else:
        hr = {"mean": 0.0, "ci_lo": 0.0, "ci_hi": 0.0, "n_runs": 0}

    lines = [
        "% Auto-generated by aedist.tabulate_macros — do not edit",
        f"\\newcommand{{\\NumModelsTested}}{{{num_models}}}",
        f"\\newcommand{{\\NumCloudModels}}{{{len(cloud_models)}}}",
        f"\\newcommand{{\\NumLocalModels}}{{{len(local_models)}}}",
        f"\\newcommand{{\\NumRefPlants}}{{{ref_plants}}}",
        f"\\newcommand{{\\BestModelName}}{{{_prettify(best_slug)}}}",
        f"\\newcommand{{\\BestModelFOne}}{{{best_f1 * 100:.1f}}}",
        f"\\newcommand{{\\BestModelFOneCI}}{{[{best_ci_str}]}}",
        f"\\newcommand{{\\BestLocalName}}{{{_prettify(best_local_slug)}}}",
        f"\\newcommand{{\\BestLocalFOne}}{{{best_local_f1 * 100:.1f}}}",
        f"\\newcommand{{\\MinBaselinePlants}}{{{min_plants}}}",
        f"\\newcommand{{\\MaxBaselinePlants}}{{{max_plants}}}",
        f"\\newcommand{{\\HeadlineModelName}}{{{_headline_pretty(headline_model)}}}",
        f"\\newcommand{{\\HeadlineMeanFOne}}{{{hr['mean'] * 100:.1f}}}",
        f"\\newcommand{{\\HeadlineCILo}}{{{hr['ci_lo'] * 100:.1f}}}",
        f"\\newcommand{{\\HeadlineCIHi}}{{{hr['ci_hi'] * 100:.1f}}}",
        f"\\newcommand{{\\HeadlineNRuns}}{{{hr['n_runs']}}}",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser(
        description="Generate LaTeX macros from measurements.jsonl",
    )
    parser.add_argument(
        "--census",
        action="store_true",
        help="Use the baseline census summary (median F1 per model, baseline "
        "models only) for the slide macros, derived from the mart directly via "
        "aedist.exp1_census — no CSV side-output (ticket 0436).",
    )
    parser.add_argument("--output", required=True, help="Path to write macros.tex")
    parser.add_argument(
        "--headline-model",
        default="deepseek-v3.2",
        help="Model slug for headline macros (default: deepseek-v3.2)",
    )
    parser.add_argument(
        "--headline-method",
        default="rag_per_fuel",
        help="Method label prefix for headline macros (default: rag_per_fuel)",
    )
    args = parser.parse_args()

    output_path = Path(args.output)

    from .exp1_census import build_census_summary
    from .measurements import load_metrics

    all_metrics = load_metrics()
    if args.census:
        summary = build_census_summary(all_metrics)
    else:
        summary = load_and_summarize(all_metrics)
    # Headline macros always need the raw run data, even for the census summary.
    headline_metrics = all_metrics

    tex = generate_macros(
        summary,
        headline_model=args.headline_model,
        headline_method=args.headline_method,
        headline_metrics=headline_metrics,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(tex)
    log.info("Wrote macros to %s (%d models)", output_path, len(summary))


if __name__ == "__main__":
    main()
