"""Generate LaTeX \\newcommand macros from all_metrics.json.

Reads per-run metrics, groups by model slug (stripping -runN suffix
and directory prefix), computes median F1, and emits macros for
the report preamble.

Usage:
    uv run python -m aedist.tabulate_macros \\
        --input results/summary/all_metrics.json \\
        --output report/inputs/generated/macros.tex
"""

import argparse
import json
import logging
import re
import statistics
from pathlib import Path

log = logging.getLogger(__name__)


def slug_from_label(label: str) -> str:
    """Extract model slug from a label like 'sweep1_census/gpt-5.4-run1'.

    Strips the directory prefix (everything up to '/') and the -runN suffix.
    """
    # Remove directory prefix
    slug = label.rsplit("/", 1)[-1]
    # Remove -runN suffix
    slug = re.sub(r"-run\d+$", "", slug)
    return slug


def load_and_summarize(metrics: list[dict]) -> dict[str, dict]:
    """Group metrics by model slug and compute median F1.

    Returns dict mapping slug -> {median_f1, is_local, runs}.
    """
    by_model: dict[str, list[float]] = {}
    for entry in metrics:
        slug = slug_from_label(entry["label"])
        by_model.setdefault(slug, []).append(entry["f1"])

    summary = {}
    for slug, f1_values in by_model.items():
        summary[slug] = {
            "median_f1": round(statistics.median(f1_values), 4),
            "is_local": slug.startswith("padme-"),
            "runs": len(f1_values),
        }
    return summary


def _prettify(slug: str) -> str:
    """Prettify a model slug for LaTeX display."""
    return slug.replace("-", " ").replace("_", " ").title()


def generate_macros(summary: dict[str, dict]) -> str:
    """Generate LaTeX \\newcommand definitions from model summary."""
    num_models = len(summary)

    # Best overall
    best_slug = max(summary, key=lambda s: summary[s]["median_f1"])
    best_f1 = summary[best_slug]["median_f1"]

    # Best local (padme- prefix)
    local_models = {s: v for s, v in summary.items() if v["is_local"]}
    if local_models:
        best_local_slug = max(local_models, key=lambda s: local_models[s]["median_f1"])
        best_local_f1 = local_models[best_local_slug]["median_f1"]
    else:
        best_local_slug = "none"
        best_local_f1 = 0.0

    lines = [
        "% Auto-generated by aedist.tabulate_macros — do not edit",
        f"\\newcommand{{\\NumModelsTested}}{{{num_models}}}",
        f"\\newcommand{{\\BestModelName}}{{{_prettify(best_slug)}}}",
        f"\\newcommand{{\\BestModelFOne}}{{{best_f1 * 100:.1f}}}",
        f"\\newcommand{{\\BestLocalName}}{{{_prettify(best_local_slug)}}}",
        f"\\newcommand{{\\BestLocalFOne}}{{{best_local_f1 * 100:.1f}}}",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser(
        description="Generate LaTeX macros from metrics JSON",
    )
    parser.add_argument("--input", required=True, help="Path to all_metrics.json")
    parser.add_argument("--output", required=True, help="Path to write macros.tex")
    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)

    with open(input_path) as f:
        metrics = json.load(f)

    summary = load_and_summarize(metrics)
    tex = generate_macros(summary)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(tex)
    log.info("Wrote %d macros to %s (%d models)", 5, output_path, len(summary))


if __name__ == "__main__":
    main()
