"""Generate LaTeX table comparing single-query vs decomposed F1 for Exp3 models.

Pipeline phase: P3 (analyze & render) — invoked by experiments/render.mk.

Reads measurements.jsonl, filters to the five models that appear in both the
``rag_extract`` (single query) and ``rag_per_fuel`` (decomposed) cohorts, and
emits a LaTeX table with median F1 and best-run F1 for each condition.

Membership choice: the five models are those that participated in the original
decomposition experiment (rag_per_fuel, 2026-05).  rag_per_fuel_v2 is a later
sweep on *different* model slugs and is deliberately excluded — mixing it with
rag_extract would conflate generations.

Column semantics:
- Méd. F1   = median F1 across runs (same convention as tab:census)
- Meilleur  = best individual run F1
- Bolding   = per-model decomposition winner (higher median F1 than single)

Ticket: 0459 (re-derive Exp3 per-model F1 comparison against v2.1).
"""

from __future__ import annotations

import argparse
import logging
import statistics
from pathlib import Path

from .measurements import SYNTHETIC_SUFFIXES, load_metrics
from .tabulate_utils import format_model_name, strip_label

log = logging.getLogger(__name__)

_DEFAULT_OUTPUT = Path("report/inputs/generated/tab_decomposition.tex")

# The five models that participated in the original decomposition experiment.
# Decision is documented here (not by accident): these are the models with
# rag_per_fuel rows in measurements.jsonl as of v2.1 (ticket 0459).
TABLE_MODELS: list[str] = [
    "mistral-small-2603",
    "gpt-5.4",
    "mistral-large-2512",
    "deepseek-v3.2",
    "gemini-2.5-flash-lite",
]


# ---------------------------------------------------------------------------
# Core computation
# ---------------------------------------------------------------------------


def _fmt_fr(value: float) -> str:
    """Format a percentage as French decimal-comma LaTeX string (e.g. '70,4\\,\\%')."""
    return f"{value * 100:.1f}\\,\\%".replace(".", ",")


def compute_decomposition_table(metrics: list[dict]) -> list[dict]:
    """Compute per-model median and best F1 for single-query and decomposed.

    Returns a list of dicts (one per model, in TABLE_MODELS order) with keys:
        slug, n_single, median_single, best_single,
        n_decomposed, median_decomposed, best_decomposed.

    Only TABLE_MODELS are included; models without data in either condition
    are skipped with a warning.  SYNTHETIC_SUFFIXES are excluded.
    """
    # Collect per-condition F1 lists
    single: dict[str, list[float]] = {}
    decomposed: dict[str, list[float]] = {}

    for entry in metrics:
        label = entry["label"]
        if any(label.endswith(s) for s in SYNTHETIC_SUFFIXES):
            continue
        slug = strip_label(label)
        if slug not in TABLE_MODELS:
            continue
        f1 = entry.get("f1")
        if f1 is None:
            continue
        if label.startswith("rag_extract/"):
            single.setdefault(slug, []).append(f1)
        elif label.startswith("rag_per_fuel/"):
            # Exclude rag_per_fuel_v2 — the prefix check is exact
            decomposed.setdefault(slug, []).append(f1)

    rows = []
    for slug in TABLE_MODELS:
        s_vals = single.get(slug, [])
        d_vals = decomposed.get(slug, [])
        if not s_vals:
            log.warning("No rag_extract rows for %s — skipping", slug)
            continue
        if not d_vals:
            log.warning("No rag_per_fuel rows for %s — skipping", slug)
            continue
        rows.append(
            {
                "slug": slug,
                "n_single": len(s_vals),
                "median_single": statistics.median(s_vals),
                "best_single": max(s_vals),
                "n_decomposed": len(d_vals),
                "median_decomposed": statistics.median(d_vals),
                "best_decomposed": max(d_vals),
            }
        )
    return rows


# ---------------------------------------------------------------------------
# LaTeX rendering
# ---------------------------------------------------------------------------


def render_latex(table: list[dict]) -> str:
    """Render compute_decomposition_table() result as a LaTeX table environment."""
    lines = [
        "% Auto-generated by aedist.tabulate_decomposition — do not edit",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\caption{Effet de la décomposition par combustible~: "
        "F1 médian et meilleur run.\\textsuperscript{a}}\\label{tab:decomposition}",
        "\\begin{tabular}{@{}lrrrr@{}}",
        "\\toprule",
        "Modèle & \\multicolumn{2}{c}{Requête unique} & \\multicolumn{2}{c}{Décomposé} \\\\",
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}",
        " & Méd.~F1 & Meilleur & Méd.~F1 & Meilleur \\\\",
        "\\midrule",
    ]

    for row in table:
        name = format_model_name(row["slug"])
        s_med = _fmt_fr(row["median_single"])
        s_best = _fmt_fr(row["best_single"])
        d_med = _fmt_fr(row["median_decomposed"])
        d_best = _fmt_fr(row["best_decomposed"])

        # Bold the decomposed pair if decomposed median > single median
        if row["median_decomposed"] > row["median_single"]:
            d_med = f"\\textbf{{{d_med}}}"
            d_best = f"\\textbf{{{d_best}}}"

        lines.append(f"{name} & {s_med} & {s_best} & {d_med} & {d_best} \\\\")

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")

    # Footnote: explain n and Méd.
    # Gather n info for the footnote
    n_notes = []
    for row in table:
        ns = row["n_single"]
        nd = row["n_decomposed"]
        if ns != nd or ns != 3:  # only note deviations from n=3
            slug_short = format_model_name(row["slug"])
            n_notes.append(f"{slug_short} décomposé $n$={nd}")
    if n_notes:
        n_footnote = "~; ".join(n_notes) + "."
    else:
        n_footnote = ""
    base_note = (
        "Meilleur = meilleur run individuel~; "
        "Méd.~F1 = médiane sur $n$~=~3 runs"
    )
    if n_notes:
        base_note += f", sauf {n_footnote}"
    else:
        base_note += "."
    lines.append("")
    lines.append(
        f"\\smallskip\n{{\\footnotesize \\textsuperscript{{a}}{base_note}}}"
    )
    lines.append("\\end{table}")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser(
        description="Generate Exp3 single-vs-decomposed F1 comparison LaTeX table",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=_DEFAULT_OUTPUT,
        help=f"Path to write the .tex file (default: {_DEFAULT_OUTPUT})",
    )
    args = parser.parse_args(argv)

    metrics = load_metrics()
    table = compute_decomposition_table(metrics)

    if not table:
        log.error("No rows generated — check measurements.jsonl for rag_extract/rag_per_fuel data")
        return

    latex = render_latex(table)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(latex)
    log.info("Wrote %s (%d model rows)", args.output, len(table))


if __name__ == "__main__":
    main()
