"""Generate internal-coherence LaTeX table from RAG extraction CSVs.

Usage:
    python -m aedist.tabulate_coherence \\
        --input experiments/outputs/rag \\
        --output report/inputs/generated/tab_coherence.tex

Loads every model-run CSV, runs ``coherence.check_coherence()`` on
each, and reports per-model median coherence rate.
"""

from __future__ import annotations

import argparse
import csv
import logging
import re
import statistics
from pathlib import Path

from .coherence import IssueLevel, check_coherence
from .evaluate import load_plants_csv
from .tabulate_utils import format_model_name

log = logging.getLogger(__name__)

_RUN_RE = re.compile(r"^(?P<model>.+)-run(?P<run>\d+)\.csv$")

# Filename prefixes/suffixes to skip (not raw per-run extractions)
_SKIP_PREFIXES = ("reconciliation_", "filtered_")
_SKIP_SUFFIXES = ("-consolidated.csv", "-union.csv")


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


def load_extractions(input_dirs: list[Path]) -> dict[str, list[tuple[int, list]]]:
    """Glob CSVs from *input_dirs*, group by model slug.

    Returns ``{model_slug: [(run_number, [Plant, ...]), ...]}``.
    Skips reconciliation / filtered / consolidated / union files.
    """
    groups: dict[str, list[tuple[int, list]]] = {}
    for d in input_dirs:
        for csv_path in sorted(d.glob("*.csv")):
            name = csv_path.name
            if any(name.startswith(p) for p in _SKIP_PREFIXES):
                continue
            if any(name.endswith(s) for s in _SKIP_SUFFIXES):
                continue
            m = _RUN_RE.match(name)
            if not m:
                continue
            model = m.group("model")
            run = int(m.group("run"))
            plants = load_plants_csv(csv_path)
            if plants:
                groups.setdefault(model, []).append((run, plants))
    return groups


# ---------------------------------------------------------------------------
# Summarisation
# ---------------------------------------------------------------------------


def summarize_coherence(extractions: dict[str, list[tuple[int, list]]]) -> list[dict]:
    """Run coherence checks per extraction, aggregate per model.

    Returns a list of dicts (one per model), sorted by coherence_rate
    descending, each containing:
        model, n_rows, n_row_issues, n_cross_row_issues, coherence_rate
    (all medians across runs).
    """
    rows: list[dict] = []
    for model, runs in sorted(extractions.items()):
        run_stats: list[dict] = []
        for _run_num, plants in runs:
            issues = check_coherence(plants)
            # Rows with at least one issue
            rows_with_issues: set[int] = set()
            n_row = 0
            n_cross = 0
            for issue in issues:
                for idx in issue.row_indices:
                    rows_with_issues.add(idx)
                if issue.level == IssueLevel.ROW:
                    n_row += 1
                elif issue.level == IssueLevel.CROSS_ROW:
                    n_cross += 1

            n_total = len(plants)
            rate = (n_total - len(rows_with_issues)) / n_total if n_total else 0.0
            run_stats.append(
                {
                    "n_rows": n_total,
                    "n_row_issues": n_row,
                    "n_cross_row_issues": n_cross,
                    "coherence_rate": rate,
                }
            )

        rows.append(
            {
                "model": model,
                "n_rows": int(statistics.median(s["n_rows"] for s in run_stats)),
                "n_row_issues": int(statistics.median(s["n_row_issues"] for s in run_stats)),
                "n_cross_row_issues": int(
                    statistics.median(s["n_cross_row_issues"] for s in run_stats)
                ),
                "coherence_rate": statistics.median(s["coherence_rate"] for s in run_stats),
            }
        )

    rows.sort(key=lambda r: r["coherence_rate"], reverse=True)
    return rows


# ---------------------------------------------------------------------------
# LaTeX rendering
# ---------------------------------------------------------------------------


def format_coherence_latex(rows: list[dict]) -> str:
    """Render a LaTeX table from summarised coherence rows."""
    lines = [
        "% Auto-generated by aedist.tabulate_coherence — do not edit",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\caption{Cohérence interne des extractions RAG (médiane sur 3 runs)."
        " Le taux de cohérence est la proportion de lignes sans problème"
        " détecté.}\\label{tab:coherence}",
        "\\begin{tabular}{@{}lrrrr@{}}",
        "\\toprule",
        "Modèle & Lignes & Pb.~ligne & Pb.~croisé & Taux \\\\",
        "\\midrule",
    ]

    for r in rows:
        name = format_model_name(r["model"])
        rate_pct = r["coherence_rate"] * 100
        lines.append(
            f"{name} & {r['n_rows']} & {r['n_row_issues']}"
            f" & {r['n_cross_row_issues']} & {rate_pct:.1f}\\% \\\\"
        )

    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
        ]
    )
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# CSV output
# ---------------------------------------------------------------------------


def write_csv(rows: list[dict], path: Path) -> None:
    """Write coherence summary to CSV."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "model",
                "n_rows",
                "n_row_issues",
                "n_cross_row_issues",
                "coherence_rate",
            ],
        )
        writer.writeheader()
        for r in rows:
            writer.writerow(r)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None):
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser(
        description="Generate internal-coherence LaTeX table from RAG CSVs",
    )
    parser.add_argument(
        "--input",
        nargs="+",
        required=True,
        help="Directories containing model-run CSVs",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Path to write tab_coherence.tex",
    )
    parser.add_argument(
        "--csv-output",
        default=None,
        help="Path to write coherence summary CSV (optional)",
    )
    args = parser.parse_args(argv)

    input_dirs = [Path(p) for p in args.input]
    output_path = Path(args.output)

    extractions = load_extractions(input_dirs)
    if not extractions:
        log.warning("No extractions found — table will be empty.")

    rows = summarize_coherence(extractions)

    latex = format_coherence_latex(rows)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(latex)
    log.info("Wrote %s (%d models)", output_path, len(rows))

    if args.csv_output:
        csv_path = Path(args.csv_output)
        write_csv(rows, csv_path)
        log.info("Wrote %s", csv_path)


if __name__ == "__main__":
    main()
