"""Generate the Exp1 status difficulty table (reference composition vs recall).

Pipeline phase: P3 (analyze & render) — invoked by experiments/render.mk.

Companion to the recognition matrix figure (ticket 0373), placed in the report
annex right after it. One row per reference-list status group:

    * status
    * n plants of that status in the reference, and its share of the list
    * mean detection probability (Exp 1, all models, memory-only) — over all
      (run x plant) cells where the plant has this status, the fraction
      recognized (TP).
    * mean detection probability (Exp 2 arm 3, single-shot with documents) —
      the same quantity over the arm-3 mart records (ticket 0628).

The point it makes: the reference list is dominated by *proposed* / pipeline
assets that memory-based recall finds hard to know, so a low mean recall is
structural, not a model failing — and the docs arm (Exp 2) lifts the long tail.

Derivation (author directive 2026-06-05): build from this table's OWN view of
the data mart by importing :mod:`aedist.exp1_recognition` — the same shared
library the matrix figure (0373) imports. Figure and table agree by common
cause (shared mart), never by consuming each other's output file. Status group
order also comes from the shared library so the table rows align with the
matrix's column bands.

Usage:
    uv run python -m aedist.tabulate_status_difficulty \\
        --records-glob "experiments/outputs/exp1_batch2/*.record.json" \\
        --reference data/reference/vietnam_thermal_plants_v2_classified.csv \\
        --output report/inputs/generated/tab_status_difficulty.tex
"""

import argparse
import logging
from pathlib import Path

from .config import VN_THERMAL_PLANTS_RELEASE_CSV
from .exp1_recognition import (
    STATUS_LABELS,
    STATUS_LABELS_EN,
    MatchDetail,
    RecognitionCell,
    load_exp1_recognition,
    status_rank,
)
from .exp2_recognition import load_exp2_recognition

log = logging.getLogger(__name__)

_REPO_ROOT = Path(__file__).parent.parent.parent


def overall_recognition_rate(rows: dict[str, tuple[int, float]]) -> float:
    """Plant-weighted mean recognition rate over all statuses.

    Each reference plant contributes the same number of cells (one per run),
    so plant-weighting per-status rates by n reproduces the cell-level overall
    mean exactly — the same quantity the matrix figure renders.
    """
    total_plants = sum(n for n, _ in rows.values())
    if not total_plants:
        return 0.0
    return sum(n * rate for n, rate in rows.values()) / total_plants


def status_accuracy_excluding_proposed(
    match_details: dict[tuple[str, int, int], MatchDetail],
) -> float:
    """Mean over runs of the per-run status accuracy on non-proposed matched cells.

    Mirrors :func:`aedist.metrics.compute_metrics` semantics — per run, the
    fraction of matched cells with ``status_match`` True among those where it
    is not None — restricted to reference plants whose status is not
    ``proposed`` (the stratum with no admissible label in the prompt's
    controlled vocabulary, tickets 0531/0534). Runs with no qualifying cell
    are skipped, exactly as ``compute_metrics`` returns None there.
    """
    per_run: dict[tuple[str, int], list[bool]] = {}
    for (model, run, _plant_id), detail in match_details.items():
        if detail.system_name is None:  # FN cell — not a matched row
            continue
        if detail.ref_status == "proposed":
            continue
        if detail.status_match is None:
            continue
        per_run.setdefault((model, run), []).append(detail.status_match)
    fracs = [sum(v) / len(v) for v in per_run.values() if v]
    if not fracs:
        raise ValueError("no matched non-proposed cells with a status comparison")
    return sum(fracs) / len(fracs)


def format_status_macros(
    rows: dict[str, tuple[int, float]],
    status_acc_excl_proposed: float,
) -> str:
    """Render the manuscript macros for the status-difficulty numbers."""
    total_plants = sum(n for n, _ in rows.values())
    n_proposed, rate_proposed = rows.get("proposed", (0, 0.0))
    share_proposed = (n_proposed / total_plants * 100.0) if total_plants else 0.0
    lines = [
        "% Auto-generated by aedist.tabulate_status_difficulty — do not edit",
        f"\\newcommand{{\\StatusProposedCount}}{{{n_proposed}}}",
        f"\\newcommand{{\\StatusProposedSharePct}}{{{share_proposed:.1f}}}",
        f"\\newcommand{{\\StatusProposedRatePct}}{{{rate_proposed * 100:.1f}}}",
        f"\\newcommand{{\\StatusOverallRatePct}}{{{overall_recognition_rate(rows) * 100:.1f}}}",
        f"\\newcommand{{\\ExpOneStatusAccExclProposed}}{{{status_acc_excl_proposed:.2f}}}",
        "",
    ]
    return "\n".join(lines)


def build_status_table(cells: list[RecognitionCell]) -> dict[str, tuple[int, float]]:
    """Aggregate recognition cells into per-status ``(n_plants, mean_rate)``.

    Args:
        cells: one :class:`RecognitionCell` per (model, run, reference plant),
            as produced by :func:`aedist.exp1_recognition.load_exp1_recognition`.

    Returns:
        Ordered mapping ``status -> (n_plants, mean_rate)`` where:
          * ``n_plants`` is the number of *distinct* reference plants of that
            status (counted by ``plant_id``, so the two same-name Formosa phases
            stay distinct — same convention as the matrix), and
          * ``mean_rate`` is the cell-level recall: recognized cells divided by
            total cells for that status, over all runs.

        Statuses are ordered by the shared :data:`STATUS_ORDER` rank (unknown
        statuses appended, then alphabetical) so rows align with the matrix's
        column bands.
    """
    plants_by_status: dict[str, set[int]] = {}
    hits_by_status: dict[str, int] = {}
    total_by_status: dict[str, int] = {}
    for c in cells:
        plants_by_status.setdefault(c.status, set()).add(c.plant_id)
        total_by_status[c.status] = total_by_status.get(c.status, 0) + 1
        if c.recognized:
            hits_by_status[c.status] = hits_by_status.get(c.status, 0) + 1

    statuses = sorted(plants_by_status, key=lambda s: (status_rank(s), s))
    rows: dict[str, tuple[int, float]] = {}
    for status in statuses:
        n_plants = len(plants_by_status[status])
        total = total_by_status[status]
        rate = hits_by_status.get(status, 0) / total if total else 0.0
        rows[status] = (n_plants, rate)
    return rows


def _rate_cell(rows: dict[str, tuple[int, float]], status: str) -> str:
    """Format one status's detection-probability cell, ``—`` if absent."""
    if status not in rows:
        return "—"
    return f"{rows[status][1] * 100:.1f}\\%"


def format_status_latex(
    rows_exp1: dict[str, tuple[int, float]],
    rows_exp2: dict[str, tuple[int, float]],
) -> str:
    """Render the per-status rows as a booktabs LaTeX table (French).

    Two detection-probability columns: Experiment~1 (all models, memory-only)
    and Experiment~2 arm~3 (single-shot with documents). Plant counts and the
    share-of-list come from the Exp~1 view (the full reference list). A status
    absent from the Exp~2 arm-3 view renders ``—``.
    """
    total_plants = sum(n for n, _ in rows_exp1.values())

    body_lines: list[str] = []
    for status, (n, rate1) in rows_exp1.items():
        label = STATUS_LABELS.get(status, status.capitalize())
        share = (n / total_plants * 100.0) if total_plants else 0.0
        cell2 = _rate_cell(rows_exp2, status)
        body_lines.append(
            f"{label} & {n} & {share:.1f}\\% & {rate1 * 100:.1f}\\% & {cell2} \\\\"
        )

    overall1 = overall_recognition_rate(rows_exp1)
    overall2 = overall_recognition_rate(rows_exp2)

    lines = [
        "% Auto-generated by aedist.tabulate_status_difficulty — do not edit",
        "\\begin{table}[htbp]",
        "\\centering",
        (
            "\\caption{Composition de la liste de référence par statut, "
            "et probabilité moyenne de détection. L'Expérience~1 couvre tous "
            "les modèles (méthode directe, mémoire seule) ; l'Expérience~2 est "
            "le bras avec documents en une passe (arm~3). Le taux est la "
            "proportion de cellules (run~$\\times$~centrale) reconnues parmi "
            "les centrales du statut.}\\label{tab:status-difficulty}"
        ),
        "\\begin{tabular}{@{}lrrrr@{}}",
        "\\toprule",
        (
            "Statut & $n$ & Part de la liste & "
            "Détection moy. (Exp.~1) & Détection moy. (Exp.~2, 1D) \\\\"
        ),
        "\\midrule",
        *body_lines,
        "\\midrule",
        (
            f"Ensemble & {total_plants} & 100.0\\% & "
            f"{overall1 * 100:.1f}\\% & {overall2 * 100:.1f}\\% \\\\"
        ),
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ]
    return "\n".join(lines)


def format_status_latex_en(
    rows_exp1: dict[str, tuple[int, float]],
    rows_exp2: dict[str, tuple[int, float]],
) -> str:
    """English manuscript table body (tabular only, ticket 0547).

    Same numbers as :func:`format_status_latex`, English labels, no float/
    caption — those stay in ``slides/manuscript/main.tex`` (0486 pattern).
    Two detection columns (Exp~1, all models; Exp~2, 1D = arm~3 single-shot
    with documents). The All row is bold.
    """
    total_plants = sum(n for n, _ in rows_exp1.values())

    body_lines: list[str] = []
    for status, (n, rate1) in rows_exp1.items():
        label = STATUS_LABELS_EN.get(status, status.capitalize())
        share = (n / total_plants * 100.0) if total_plants else 0.0
        cell2 = _rate_cell(rows_exp2, status)
        body_lines.append(
            f"{label} & {n} & {share:.1f}\\% & {rate1 * 100:.1f}\\% & {cell2} \\\\"
        )

    overall1 = overall_recognition_rate(rows_exp1)
    overall2 = overall_recognition_rate(rows_exp2)
    lines = [
        "% Auto-generated by aedist.tabulate_status_difficulty — do not edit",
        "\\begin{tabular}{@{}lrrrr@{}}",
        "\\toprule",
        (
            "Status & n & Share of list & "
            "Avg. detection prob. (Exp 1) & Avg. detection prob. (Exp 2, 1D) \\\\"
        ),
        "\\midrule",
        *body_lines,
        "\\midrule",
        (
            f"\\textbf{{All}} & \\textbf{{{total_plants}}} & \\textbf{{100.0\\%}} & "
            f"\\textbf{{{overall1 * 100:.1f}\\%}} & \\textbf{{{overall2 * 100:.1f}\\%}} \\\\"
        ),
        "\\bottomrule",
        "\\end{tabular}",
        "",
    ]
    return "\n".join(lines)


def write_table(
    records_glob: str,
    reference_path: Path,
    output: Path,
    mart_jsonl: Path,
    repo_root: Path,
    output_macros: Path | None = None,
    output_body_en: Path | None = None,
) -> None:
    """Build the status difficulty table from the mart and write the LaTeX file.

    Two detection columns: Experiment~1 (all models, memory-only) from
    ``records_glob`` via :func:`aedist.exp1_recognition.load_exp1_recognition`,
    and Experiment~2 arm~3 (single-shot with documents) from ``mart_jsonl`` via
    :func:`aedist.exp2_recognition.load_exp2_recognition`. No new pipeline: the
    arm-3 records are already in the mart (author directive 2026-06-15).

    When ``output_macros`` is given, the single Exp~1 reconcile pass also
    collects per-cell match details so the macros file can carry the
    status-accuracy-excluding-proposed value (no second LP run). The macros
    remain Exp~1 only — they back the §7.1 register-shape prose.
    """
    data = load_exp1_recognition(
        records_glob, reference_path, collect_details=output_macros is not None
    )
    if not data.cells:
        log.warning("No recognition data for pattern: %s", records_glob)
        return
    rows = build_status_table(data.cells)

    data_exp2 = load_exp2_recognition(mart_jsonl, reference_path, repo_root, arm="arm3")
    rows_exp2 = build_status_table(data_exp2.cells)

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(format_status_latex(rows, rows_exp2), encoding="utf-8")
    log.info("Wrote status difficulty table to %s", output)
    for status, (n, rate) in rows.items():
        log.info("  %-13s n=%3d  rate=%.3f", status, n, rate)

    if output_body_en is not None:
        output_body_en.parent.mkdir(parents=True, exist_ok=True)
        output_body_en.write_text(format_status_latex_en(rows, rows_exp2), encoding="utf-8")
        log.info("Wrote English status difficulty table body to %s", output_body_en)

    if output_macros is not None:
        acc = status_accuracy_excluding_proposed(data.match_details)
        output_macros.parent.mkdir(parents=True, exist_ok=True)
        output_macros.write_text(format_status_macros(rows, acc), encoding="utf-8")
        log.info("Wrote status difficulty macros to %s (excl-proposed acc=%.4f)", output_macros, acc)


def main(argv: list[str] | None = None) -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser(
        description="Generate the Exp1 status difficulty table (reference composition vs recall)"
    )
    parser.add_argument(
        "--records-glob",
        default="experiments/outputs/exp1_batch2/*.record.json",
        help="Glob for exp1_batch2 record.json files",
    )
    parser.add_argument(
        "--reference",
        type=Path,
        default=VN_THERMAL_PLANTS_RELEASE_CSV,
        help="Reference CSV (gold list); read at build time, no hardcoded count",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=_REPO_ROOT / "report" / "inputs" / "generated" / "tab_status_difficulty.tex",
        help="Output .tex path",
    )
    parser.add_argument(
        "--output-macros",
        type=Path,
        default=_REPO_ROOT / "report" / "inputs" / "generated" / "macros_status_difficulty.tex",
        help="Output LaTeX macros file for the manuscript (ticket 0531)",
    )
    parser.add_argument(
        "--output-body-en",
        type=Path,
        default=_REPO_ROOT / "report" / "inputs" / "generated" / "tab_status_difficulty_en.tex",
        help="Output English table body (tabular only) for the manuscript (ticket 0547)",
    )
    parser.add_argument(
        "--mart-jsonl",
        type=Path,
        default=_REPO_ROOT / "experiments" / "derived" / "exp2_mart.jsonl",
        help="Exp2 mart JSONL (P2 outcome); source of the arm-3 detection column",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=_REPO_ROOT,
        help="Repository root used to resolve arm-3 artifact paths in the mart",
    )
    args = parser.parse_args(argv)

    write_table(
        records_glob=args.records_glob,
        reference_path=args.reference,
        output=args.output,
        mart_jsonl=args.mart_jsonl,
        repo_root=args.repo_root,
        output_macros=args.output_macros,
        output_body_en=args.output_body_en,
    )


if __name__ == "__main__":
    main()
