"""Generate self-consistency LaTeX table from measurements.jsonl.

Usage:
    python -m aedist.tabulate_self_consistency \\
        --measurements measurements.jsonl \\
        --output report/inputs/generated/tab_self_consistency.tex

Reads per-run metrics from sweep_rag and vote results from
sweep_rag_consistency, groups by model, computes medians at render time,
and emits a LaTeX table showing single-run medians vs majority/union vote F1.
"""

import argparse
import logging
import re
import statistics
from pathlib import Path

from .tabulate_utils import format_model_name

log = logging.getLogger(__name__)

# Threshold for classifying failure regime: ≥95% means "near-perfect"
_REGIME_THRESHOLD = 0.95


def _regime(r: dict) -> str:
    """Classify a model as truncation-limited or overgeneration-limited.

    Truncation: median precision ~100%, low recall.
    Overgeneration: median recall ~100%, low precision.
    """
    if r["median_precision"] >= _REGIME_THRESHOLD:
        return "truncation"
    if r["median_coverage"] >= _REGIME_THRESHOLD:
        return "overgeneration"
    return "mixed"


def generate_self_consistency_table(results: list[dict]) -> str:
    """Generate LaTeX table from self-consistency summary."""
    results_sorted = sorted(results, key=lambda r: r["median_f1"], reverse=True)

    lines = [
        "% Auto-generated by aedist.tabulate_self_consistency — do not edit",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\caption{Self-consistency: median single-run F1 vs.~majority and union"
        " vote (RAG, 3 runs per model). Regime indicates the dominant failure"
        " mode.}\\label{tab:self-consistency}",
        "\\begin{tabular}{@{}lrrrrl@{}}",
        "\\toprule",
        "Model & Med.~F1 & Maj.~F1 & Union F1 & Best $\\Delta$ & Regime \\\\",
        "\\midrule",
    ]

    for r in results_sorted:
        name = format_model_name(r["model"])
        med_f1 = r["median_f1"] * 100
        maj_f1 = (r.get("majority_f1") or 0) * 100
        union_f1 = (r.get("union_f1") or 0) * 100

        regime = _regime(r)

        if regime == "overgeneration":
            best_delta = maj_f1 - med_f1
        else:
            best_delta = union_f1 - med_f1

        delta_str = f"{best_delta:+.1f}\\%"

        lines.append(
            f"{name} & {med_f1:.1f}\\% & {maj_f1:.1f}\\% & {union_f1:.1f}\\%"
            f" & {delta_str} & {regime} \\\\"
        )

    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
        ]
    )
    return "\n".join(lines) + "\n"


def generate_per_run_table(results: list[dict]) -> str:
    """Generate a detailed per-run LaTeX table.

    Shows individual run F1 scores, number of plants matched, missed, and
    hallucinated for each run.
    """
    lines = [
        "% Auto-generated by aedist.tabulate_self_consistency — do not edit",
        "\\begin{longtable}[]{@{}lrrrrrr@{}}",
        "\\caption{Per-run breakdown: sweep2\\_rag, 5 models $\\times$ 3 runs"
        " (sorted by F1 within each model)."
        " Truncation-limited models show 100\\% precision with varying recall;"
        " overgeneration-limited models show 100\\% recall with varying"
        " precision.}\\label{tab:per-run}\\\\",
        "\\toprule",
        "Model & Plants & Matched & Missed & Halluc. & Recall & F1 \\\\",
        "\\midrule",
        "\\endhead",
        "\\bottomrule",
        "\\endlastfoot",
    ]

    for r in sorted(results, key=lambda r: r["median_f1"], reverse=True):
        name = format_model_name(r["model"])
        n_ref = r.get("n_reference", 163)
        n_runs = r["n_valid_runs"]
        for i in range(n_runs):
            f1 = r["run_f1_scores"][i] * 100
            matched = r["run_n_matched"][i]
            n_sys = r["run_n_system"][i]
            missed = n_ref - matched
            halluc = n_sys - matched
            recall = matched / n_ref * 100 if n_ref > 0 else 0

            run_label = name if i == 0 else ""
            lines.append(
                f"{run_label} & {n_sys}"
                f" & {matched} & {missed} & {halluc}"
                f" & {recall:.1f}\\% & {f1:.1f}\\% \\\\"
            )
        lines.append("\\addlinespace")

    lines.append("\\end{longtable}")
    return "\n".join(lines) + "\n"


def _strip_run_suffix(label: str) -> str:
    """Strip -runN suffix and directory prefix to get model slug."""

    stem = label.rsplit("/", 1)[-1]
    return re.sub(r"-run\d+$", "", stem)


def _strip_vote_suffix(label: str) -> str:
    """Strip -consolidated or -union suffix from a label stem."""
    stem = label.rsplit("/", 1)[-1]
    for suffix in ("-consolidated", "-union"):
        if stem.endswith(suffix):
            return stem[: -len(suffix)]
    return stem


def assemble_from_measurements(metrics: list[dict]) -> list[dict]:
    """Build self-consistency result dicts from measurements.jsonl records.

    Expects dicts from the adapter with labels like:
    - sweep_rag/deepseek-v3.2-run1  (per-run)
    - sweep_rag_consistency/deepseek-v3.2-consolidated  (majority vote)
    - sweep_rag_consistency/deepseek-v3.2-union  (union vote)
    """

    # Separate per-run and vote records
    per_run: dict[str, list[dict]] = {}
    consolidated: dict[str, dict] = {}
    union: dict[str, dict] = {}

    for m in metrics:
        label = m.get("label", "")
        if label.startswith("sweep_rag_consistency/"):
            model = _strip_vote_suffix(label)
            if label.endswith("-consolidated"):
                consolidated[model] = m
            elif label.endswith("-union"):
                union[model] = m
        elif label.startswith("sweep_rag/"):
            model = _strip_run_suffix(label)
            per_run.setdefault(model, []).append(m)

    results = []
    for model in sorted(per_run):
        runs = sorted(per_run[model], key=lambda r: r.get("f1", 0))
        f1_scores = [r["f1"] for r in runs]
        coverages = [r.get("coverage", 0) for r in runs]
        precisions = [r.get("precision", 0) for r in runs]

        cons = consolidated.get(model, {})
        uni = union.get(model, {})

        results.append(
            {
                "model": model,
                "n_reference": runs[0].get("n_reference", 163) if runs else 163,
                "n_runs": len(runs),
                "n_valid_runs": len(runs),
                "run_f1_scores": f1_scores,
                "run_n_matched": [r.get("n_matched", 0) for r in runs],
                "run_n_system": [r.get("n_system", 0) for r in runs],
                "median_f1": round(statistics.median(f1_scores), 4),
                "median_coverage": round(statistics.median(coverages), 4),
                "median_precision": round(statistics.median(precisions), 4),
                "majority_f1": cons.get("f1"),
                "majority_coverage": cons.get("coverage"),
                "majority_precision": cons.get("precision"),
                "majority_n_matched": cons.get("n_matched"),
                "majority_n_system": cons.get("n_system"),
                "majority_n_hallucinated": cons.get("n_hallucinated"),
                "n_majority_plants": cons.get("n_system", 0),
                "union_f1": uni.get("f1"),
                "union_coverage": uni.get("coverage"),
                "union_precision": uni.get("precision"),
                "union_n_matched": uni.get("n_matched"),
                "union_n_system": uni.get("n_system"),
                "union_n_hallucinated": uni.get("n_hallucinated"),
            }
        )

    return results


def main(argv: list[str] | None = None):
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser(
        description="Generate self-consistency LaTeX tables",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Path to write tab_self_consistency.tex",
    )
    parser.add_argument(
        "--per-run-output",
        default=None,
        help="Path to write tab_per_run.tex (optional)",
    )
    args = parser.parse_args(argv)

    from .measurements import load_metrics

    output_path = Path(args.output)

    metrics = load_metrics()
    results = assemble_from_measurements(metrics)

    latex = generate_self_consistency_table(results)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(latex)
    log.info("Wrote %s (%d models)", output_path, len(results))

    if args.per_run_output:
        per_run_path = Path(args.per_run_output)
        per_run_latex = generate_per_run_table(results)
        per_run_path.write_text(per_run_latex)
        log.info("Wrote %s", per_run_path)


if __name__ == "__main__":
    main()
