"""Emit the reference-register manuscript macros (count and fuel split).

Pipeline phase: P3 (analyze & render) — invoked by experiments/render.mk.

Writes ``report/inputs/generated/macros_reference.tex`` with:

- ``\\NumRefPlants``  — the adopted reference release size, via
  :func:`aedist.evaluate.reference_plant_count` (the single source of truth —
  never a hardcoded count, ticket 0501/0531);
- ``\\RefCoalCount``  — plants with ``fuel == coal``;
- ``\\RefGasOilCount`` — all non-coal plants (gas + gas/oil).

The 0531 adherence test (``tests/test_manuscript_macros.py``) re-derives all
three from the CSV by an independent parse and asserts the fragment matches.

Usage::

    uv run python -m aedist.tabulate_reference_macros \\
        --reference data/reference/vietnam_thermal_plants_v2_classified.csv \\
        --output report/inputs/generated/macros_reference.tex
"""

import argparse
import csv
import logging
from pathlib import Path

from .config import VN_THERMAL_PLANTS_RELEASE_CSV
from .evaluate import reference_plant_count

log = logging.getLogger(__name__)

_REPO_ROOT = Path(__file__).parent.parent.parent

# The fuel vocabulary \RefGasOilCount assumes: everything non-coal is gas or
# gas/oil. A new fuel value must extend the macros, not be absorbed silently.
_KNOWN_FUELS = {"coal", "gas", "gas/oil"}


def generate_macros(reference: Path) -> str:
    """Render the macros from the reference CSV.

    The count comes from ``reference_plant_count`` (schema-validated rows);
    the fuel split is a direct column count. If schema validation ever drops
    a row, the two disagree and the adherence test flags it.
    """
    n_plants = reference_plant_count(reference)
    with reference.open(newline="", encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    fuels = {(r.get("fuel") or "").strip() for r in rows}
    unknown = fuels - _KNOWN_FUELS
    assert not unknown, (
        f"unexpected fuel value(s) {sorted(unknown)} in {reference.name}; "
        "\\RefGasOilCount counts all non-coal rows — extend the macros instead"
    )
    coal = sum(1 for r in rows if (r.get("fuel") or "").strip() == "coal")
    gas_oil = len(rows) - coal
    return (
        "% Auto-generated by aedist.tabulate_reference_macros — do not edit.\n"
        f"\\newcommand{{\\NumRefPlants}}{{{n_plants}}}\n"
        f"\\newcommand{{\\RefCoalCount}}{{{coal}}}\n"
        f"\\newcommand{{\\RefGasOilCount}}{{{gas_oil}}}\n"
    )


def main(argv: list[str] | None = None) -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser(
        description="Emit the reference-register manuscript macros (count + fuel split)"
    )
    parser.add_argument(
        "--reference",
        type=Path,
        default=VN_THERMAL_PLANTS_RELEASE_CSV,
        help="Reference CSV (gold list); read at build time, no hardcoded count",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=_REPO_ROOT / "report" / "inputs" / "generated" / "macros_reference.tex",
        help="Output .tex path",
    )
    args = parser.parse_args(argv)

    text = generate_macros(args.reference)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")
    log.info("Wrote %s:\n%s", args.output, text)


if __name__ == "__main__":
    main()
