"""Write Experiment 1 run-level F1 summary macros from the committed cross-eval CSV.

Pipeline phase: P3 (analyze & render) — invoked by experiments/render.mk.

Reads ``experiments/derived/exp1_cross_eval.csv`` (the canonical batch-2
scoring CSV, 14 models × 5 repetitions = 70 runs) and emits
``report/inputs/generated/macros_exp1_run_stats.tex`` with:

- ``\\ExpOneFOneMin``   — minimum F1 across all usable runs (2 d.p.)
- ``\\ExpOneFOneMean``  — mean F1 across all usable runs (2 d.p.)
- ``\\ExpOneFOneMax``   — maximum F1 across all usable runs (2 d.p.)
- ``\\ExpOneNRuns``     — total number of usable runs (integer)
- ``\\ExpOneNModels``   — number of distinct models (integer)

The ticket-0474 adherence test (``test_abstract_numbers.py``) re-parses this
file independently and asserts that the manuscript abstract's numeric literals
match.

Usage::

    uv run python -m aedist.tabulate_exp1_run_stats \\
        --cross-eval experiments/derived/exp1_cross_eval.csv \\
        --output report/inputs/generated/macros_exp1_run_stats.tex
"""

import argparse
import csv
import logging
from pathlib import Path

log = logging.getLogger(__name__)


def _load_f1_stats(cross_eval: Path) -> dict:
    """Load F1 statistics from exp1_cross_eval.csv.

    Returns a dict with keys: f1_min, f1_mean, f1_max, n_runs, n_models.
    Rows with an empty accuracy_f1 field are skipped (should not occur in
    the canonical CSV but guards against future format changes).
    """
    rows = list(csv.DictReader(cross_eval.open(encoding="utf-8")))
    f1_vals = [float(r["accuracy_f1"]) for r in rows if r.get("accuracy_f1")]
    if not f1_vals:
        raise ValueError(f"No F1 values found in {cross_eval}")
    n_models = len({r["model"] for r in rows if r.get("model")})
    return {
        "f1_min": min(f1_vals),
        "f1_mean": sum(f1_vals) / len(f1_vals),
        "f1_max": max(f1_vals),
        "n_runs": len(f1_vals),
        "n_models": n_models,
    }


def _write_macros(stats: dict, output: Path) -> None:
    """Emit the LaTeX macro file."""
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        "% Auto-generated by aedist.tabulate_exp1_run_stats — do not edit.\n"
        f"\\newcommand{{\\ExpOneFOneMin}}{{{stats['f1_min']:.2f}}}\n"
        f"\\newcommand{{\\ExpOneFOneMean}}{{{stats['f1_mean']:.2f}}}\n"
        f"\\newcommand{{\\ExpOneFOneMax}}{{{stats['f1_max']:.2f}}}\n"
        f"\\newcommand{{\\ExpOneNRuns}}{{{stats['n_runs']}}}\n"
        f"\\newcommand{{\\ExpOneNModels}}{{{stats['n_models']}}}\n",
        encoding="utf-8",
    )
    log.info("Wrote %s", output)


def main(argv: list[str] | None = None) -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser(
        description="Write Exp1 run-level F1 summary macros from cross-eval CSV",
    )
    parser.add_argument(
        "--cross-eval",
        default="experiments/derived/exp1_cross_eval.csv",
        help="Path to exp1_cross_eval.csv (default: experiments/derived/exp1_cross_eval.csv)",
    )
    parser.add_argument(
        "--output",
        default="report/inputs/generated/macros_exp1_run_stats.tex",
        help="Path to write macros_exp1_run_stats.tex",
    )
    args = parser.parse_args(argv)
    stats = _load_f1_stats(Path(args.cross_eval))
    _write_macros(stats, Path(args.output))
    log.info(
        "Exp1 F1: min=%.2f mean=%.2f max=%.2f  n_runs=%d  n_models=%d",
        stats["f1_min"],
        stats["f1_mean"],
        stats["f1_max"],
        stats["n_runs"],
        stats["n_models"],
    )


if __name__ == "__main__":
    main()
