"""Generate the Exp1 status difficulty table (reference composition vs recall).

Pipeline phase: P3 (analyze & render) — invoked by experiments/render.mk.

Companion to the recognition matrix figure (ticket 0373), placed in the report
annex right after it. One row per reference-list status group:

    * status
    * n plants of that status in the reference, and its share of the list
    * mean recognition rate — over all (run x plant) cells where the plant has
      this status, the fraction recognized (TP).

The point it makes: the reference list is dominated by *proposed* / pipeline
assets that memory-based recall cannot know, so a low mean recall is structural,
not a model failing.

Derivation (author directive 2026-06-05): build from this table's OWN view of
the data mart by importing :mod:`aedist.exp1_recognition` — the same shared
library the matrix figure (0373) imports. Figure and table agree by common
cause (shared mart), never by consuming each other's output file. Status group
order also comes from the shared library so the table rows align with the
matrix's column bands.

Usage:
    uv run python -m aedist.tabulate_status_difficulty \\
        --records-glob "experiments/outputs/exp1_batch2/*.record.json" \\
        --reference data/reference/vietnam_thermal_plants_v2_classified.csv \\
        --output report/inputs/generated/tab_status_difficulty.tex
"""

import argparse
import logging
from pathlib import Path

from .config import VN_THERMAL_PLANTS_RELEASE_CSV
from .exp1_recognition import (
    STATUS_LABELS,
    STATUS_LABELS_EN,
    MatchDetail,
    RecognitionCell,
    load_exp1_recognition,
    status_rank,
)

log = logging.getLogger(__name__)

_REPO_ROOT = Path(__file__).parent.parent.parent


def overall_recognition_rate(rows: dict[str, tuple[int, float]]) -> float:
    """Plant-weighted mean recognition rate over all statuses.

    Each reference plant contributes the same number of cells (one per run),
    so plant-weighting per-status rates by n reproduces the cell-level overall
    mean exactly — the same quantity the matrix figure renders.
    """
    total_plants = sum(n for n, _ in rows.values())
    if not total_plants:
        return 0.0
    return sum(n * rate for n, rate in rows.values()) / total_plants


def status_accuracy_excluding_proposed(
    match_details: dict[tuple[str, int, int], MatchDetail],
) -> float:
    """Mean over runs of the per-run status accuracy on non-proposed matched cells.

    Mirrors :func:`aedist.metrics.compute_metrics` semantics — per run, the
    fraction of matched cells with ``status_match`` True among those where it
    is not None — restricted to reference plants whose status is not
    ``proposed`` (the stratum with no admissible label in the prompt's
    controlled vocabulary, tickets 0531/0534). Runs with no qualifying cell
    are skipped, exactly as ``compute_metrics`` returns None there.
    """
    per_run: dict[tuple[str, int], list[bool]] = {}
    for (model, run, _plant_id), detail in match_details.items():
        if detail.system_name is None:  # FN cell — not a matched row
            continue
        if detail.ref_status == "proposed":
            continue
        if detail.status_match is None:
            continue
        per_run.setdefault((model, run), []).append(detail.status_match)
    fracs = [sum(v) / len(v) for v in per_run.values() if v]
    if not fracs:
        raise ValueError("no matched non-proposed cells with a status comparison")
    return sum(fracs) / len(fracs)


def format_status_macros(
    rows: dict[str, tuple[int, float]],
    status_acc_excl_proposed: float,
) -> str:
    """Render the manuscript macros for the status-difficulty numbers."""
    total_plants = sum(n for n, _ in rows.values())
    n_proposed, rate_proposed = rows.get("proposed", (0, 0.0))
    share_proposed = (n_proposed / total_plants * 100.0) if total_plants else 0.0
    lines = [
        "% Auto-generated by aedist.tabulate_status_difficulty — do not edit",
        f"\\newcommand{{\\StatusProposedCount}}{{{n_proposed}}}",
        f"\\newcommand{{\\StatusProposedSharePct}}{{{share_proposed:.1f}}}",
        f"\\newcommand{{\\StatusProposedRatePct}}{{{rate_proposed * 100:.1f}}}",
        f"\\newcommand{{\\StatusOverallRatePct}}{{{overall_recognition_rate(rows) * 100:.1f}}}",
        f"\\newcommand{{\\ExpOneStatusAccExclProposed}}{{{status_acc_excl_proposed:.2f}}}",
        "",
    ]
    return "\n".join(lines)


def build_status_table(cells: list[RecognitionCell]) -> dict[str, tuple[int, float]]:
    """Aggregate recognition cells into per-status ``(n_plants, mean_rate)``.

    Args:
        cells: one :class:`RecognitionCell` per (model, run, reference plant),
            as produced by :func:`aedist.exp1_recognition.load_exp1_recognition`.

    Returns:
        Ordered mapping ``status -> (n_plants, mean_rate)`` where:
          * ``n_plants`` is the number of *distinct* reference plants of that
            status (counted by ``plant_id``, so the two same-name Formosa phases
            stay distinct — same convention as the matrix), and
          * ``mean_rate`` is the cell-level recall: recognized cells divided by
            total cells for that status, over all runs.

        Statuses are ordered by the shared :data:`STATUS_ORDER` rank (unknown
        statuses appended, then alphabetical) so rows align with the matrix's
        column bands.
    """
    plants_by_status: dict[str, set[int]] = {}
    hits_by_status: dict[str, int] = {}
    total_by_status: dict[str, int] = {}
    for c in cells:
        plants_by_status.setdefault(c.status, set()).add(c.plant_id)
        total_by_status[c.status] = total_by_status.get(c.status, 0) + 1
        if c.recognized:
            hits_by_status[c.status] = hits_by_status.get(c.status, 0) + 1

    statuses = sorted(plants_by_status, key=lambda s: (status_rank(s), s))
    rows: dict[str, tuple[int, float]] = {}
    for status in statuses:
        n_plants = len(plants_by_status[status])
        total = total_by_status[status]
        rate = hits_by_status.get(status, 0) / total if total else 0.0
        rows[status] = (n_plants, rate)
    return rows


def format_status_latex(rows: dict[str, tuple[int, float]]) -> str:
    """Render the per-status ``(n, rate)`` rows as a booktabs LaTeX table.

    Adds a per-status share-of-list column (computed here, not stored in
    ``rows``) and a closing total row over the whole reference list.
    """
    total_plants = sum(n for n, _ in rows.values())

    body_lines: list[str] = []
    for status, (n, rate) in rows.items():
        label = STATUS_LABELS.get(status, status.capitalize())
        share = (n / total_plants * 100.0) if total_plants else 0.0
        body_lines.append(f"{label} & {n} & {share:.1f}\\% & {rate * 100:.1f}\\% \\\\")

    overall_rate = overall_recognition_rate(rows)

    lines = [
        "% Auto-generated by aedist.tabulate_status_difficulty — do not edit",
        "\\begin{table}[htbp]",
        "\\centering",
        (
            "\\caption{Composition de la liste de référence par statut, "
            "et taux de reconnaissance moyen (Expérience~1, méthode directe~: "
            "les 14~modèles à cinq répétitions). Le taux est la proportion de "
            "cellules (run~$\\times$~centrale) reconnues parmi les centrales du "
            "statut. La liste est dominée par les centrales en projet, que la "
            "mémoire des modèles ne peut connaître.}\\label{tab:status-difficulty}"
        ),
        "\\begin{tabular}{@{}lrrr@{}}",
        "\\toprule",
        "Statut & $n$ & Part de la liste & Taux de reconnaissance \\\\",
        "\\midrule",
        *body_lines,
        "\\midrule",
        f"Ensemble & {total_plants} & 100.0\\% & {overall_rate * 100:.1f}\\% \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ]
    return "\n".join(lines)


def format_status_latex_en(rows: dict[str, tuple[int, float]]) -> str:
    """English manuscript table body (tabular only, ticket 0547).

    Same numbers as :func:`format_status_latex`, English labels, no float/
    caption — those stay in ``slides/manuscript/main.tex`` (0486 pattern).
    The All row is bold.
    """
    total_plants = sum(n for n, _ in rows.values())

    body_lines: list[str] = []
    for status, (n, rate) in rows.items():
        label = STATUS_LABELS_EN.get(status, status.capitalize())
        share = (n / total_plants * 100.0) if total_plants else 0.0
        body_lines.append(f"{label} & {n} & {share:.1f}\\% & {rate * 100:.1f}\\% \\\\")

    overall_rate = overall_recognition_rate(rows)
    lines = [
        "% Auto-generated by aedist.tabulate_status_difficulty — do not edit",
        "\\begin{tabular}{@{}lrrr@{}}",
        "\\toprule",
        "Status & n & Share of list & Recognition rate \\\\",
        "\\midrule",
        *body_lines,
        "\\midrule",
        (
            f"\\textbf{{All}} & \\textbf{{{total_plants}}} & \\textbf{{100.0\\%}} & "
            f"\\textbf{{{overall_rate * 100:.1f}\\%}} \\\\"
        ),
        "\\bottomrule",
        "\\end{tabular}",
        "",
    ]
    return "\n".join(lines)


def write_table(
    records_glob: str,
    reference_path: Path,
    output: Path,
    output_macros: Path | None = None,
    output_body_en: Path | None = None,
) -> None:
    """Build the status difficulty table from the mart and write the LaTeX file.

    When ``output_macros`` is given, the single reconcile pass also collects
    per-cell match details so the macros file can carry the
    status-accuracy-excluding-proposed value (no second LP run).
    """
    data = load_exp1_recognition(
        records_glob, reference_path, collect_details=output_macros is not None
    )
    if not data.cells:
        log.warning("No recognition data for pattern: %s", records_glob)
        return
    rows = build_status_table(data.cells)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(format_status_latex(rows), encoding="utf-8")
    log.info("Wrote status difficulty table to %s", output)
    for status, (n, rate) in rows.items():
        log.info("  %-13s n=%3d  rate=%.3f", status, n, rate)

    if output_body_en is not None:
        output_body_en.parent.mkdir(parents=True, exist_ok=True)
        output_body_en.write_text(format_status_latex_en(rows), encoding="utf-8")
        log.info("Wrote English status difficulty table body to %s", output_body_en)

    if output_macros is not None:
        acc = status_accuracy_excluding_proposed(data.match_details)
        output_macros.parent.mkdir(parents=True, exist_ok=True)
        output_macros.write_text(format_status_macros(rows, acc), encoding="utf-8")
        log.info("Wrote status difficulty macros to %s (excl-proposed acc=%.4f)", output_macros, acc)


def main(argv: list[str] | None = None) -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser(
        description="Generate the Exp1 status difficulty table (reference composition vs recall)"
    )
    parser.add_argument(
        "--records-glob",
        default="experiments/outputs/exp1_batch2/*.record.json",
        help="Glob for exp1_batch2 record.json files",
    )
    parser.add_argument(
        "--reference",
        type=Path,
        default=VN_THERMAL_PLANTS_RELEASE_CSV,
        help="Reference CSV (gold list); read at build time, no hardcoded count",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=_REPO_ROOT / "report" / "inputs" / "generated" / "tab_status_difficulty.tex",
        help="Output .tex path",
    )
    parser.add_argument(
        "--output-macros",
        type=Path,
        default=_REPO_ROOT / "report" / "inputs" / "generated" / "macros_status_difficulty.tex",
        help="Output LaTeX macros file for the manuscript (ticket 0531)",
    )
    parser.add_argument(
        "--output-body-en",
        type=Path,
        default=_REPO_ROOT / "report" / "inputs" / "generated" / "tab_status_difficulty_en.tex",
        help="Output English table body (tabular only) for the manuscript (ticket 0547)",
    )
    args = parser.parse_args(argv)

    write_table(
        records_glob=args.records_glob,
        reference_path=args.reference,
        output=args.output,
        output_macros=args.output_macros,
        output_body_en=args.output_body_en,
    )


if __name__ == "__main__":
    main()
