"""Generate Annex A reasoning-tokens + interday-variability table.

Joins two cohorts of Experiment 1 runs:
- baseline: ``outputs/ablation/direct/p1_base/``  (2026-05-20, N=5)
- topup:    ``outputs/ablation/direct/p1_base.topup/``  (2026-05-21, N≤3)

Per model, computes:
- F1 mean/sd for each cohort (over reps with status=ok)
- Interday delta = topup_mean − baseline_mean
- Reasoning tokens median over the topup cohort (post-fix only)
- N valid reps per cohort

Usage:
    python -m aedist.tabulate_exp1_reasoning_topup \\
        --measurements ../measurements.jsonl \\
        --output ../report/inputs/generated/tab_exp1_reasoning_topup.tex
"""

import argparse
import json
import logging
import statistics
from pathlib import Path

from .tabulate_utils import format_model_name

log = logging.getLogger(__name__)

BASELINE_PREFIX = "experiments/outputs/ablation/direct/p1_base/"
TOPUP_PREFIX = "experiments/outputs/ablation/direct/p1_base.topup/"
PILOT_MARKER = "/p1_base.pilot/"


def _cohort(rec: dict) -> str | None:
    rf = rec.get("result_file", "") or ""
    if PILOT_MARKER in rf:
        return None
    if rf.startswith(TOPUP_PREFIX):
        return "topup"
    if rf.startswith(BASELINE_PREFIX):
        return "baseline"
    return None


def aggregate(records: list[dict]) -> list[dict]:
    by_model: dict[str, dict] = {}
    for rec in records:
        cohort = _cohort(rec)
        if cohort is None:
            continue
        mp = rec.get("method_params") or {}
        if not isinstance(mp, dict):
            continue
        model = mp.get("model")
        if not model:
            continue
        ru = rec.get("resource_use") or {}
        rs = rec.get("result_summary") or {}
        agg = by_model.setdefault(
            model,
            {
                "model": model,
                "baseline_f1": [],
                "baseline_n_total": 0,
                "topup_f1": [],
                "topup_n_total": 0,
                "topup_thinking_tokens": [],
                "topup_cost_usd": [],
            },
        )
        agg[f"{cohort}_n_total"] += 1
        if rs.get("status") == "ok" and rs.get("f1") is not None:
            agg[f"{cohort}_f1"].append(float(rs["f1"]))
        if cohort == "topup":
            tt = ru.get("thinking_tokens")
            if tt is not None:
                agg["topup_thinking_tokens"].append(int(tt))
            cost = ru.get("cost_usd")
            if cost is not None:
                agg["topup_cost_usd"].append(float(cost))
    return sorted(by_model.values(), key=lambda r: r["model"])


def _mean_sd(vals: list[float]) -> tuple[float | None, float | None]:
    if not vals:
        return None, None
    if len(vals) == 1:
        return vals[0], 0.0
    return statistics.mean(vals), statistics.stdev(vals)


def _fmt_f1(mean: float | None, sd: float | None, n: int) -> str:
    if mean is None:
        return "---"
    if n == 1 or sd == 0.0:
        return f"{mean:.3f}"
    return f"{mean:.3f}\\,$\\pm$\\,{sd:.3f}"


def _fmt_delta(baseline_mean: float | None, topup_mean: float | None) -> str:
    if baseline_mean is None or topup_mean is None:
        return "---"
    delta = topup_mean - baseline_mean
    sign = "+" if delta >= 0 else ""
    return f"{sign}{delta:.3f}"


def _fmt_int_or_dash(val: int | None) -> str:
    if val is None:
        return "---"
    return f"{val:,}".replace(",", "\\,")


def _fmt_n(n_valid: int, n_total: int) -> str:
    if n_valid == n_total:
        return str(n_total)
    return f"{n_valid}/{n_total}"


def generate_table_tex(rows: list[dict]) -> str:
    lines = [
        "% Auto-generated by aedist.tabulate_exp1_reasoning_topup — do not edit",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\small",
        "\\caption{Experiment~1 results, pooled across the 2026-05-20 baseline "
        "($N{\\leq}5$) and a 2026-05-21 post-fix top-up cohort ($N{\\leq}3$). "
        "The post-fix cohort captures \\texttt{reasoning\\_tokens} via the "
        "OpenRouter \\texttt{completion\\_tokens\\_details} channel (PR\\#379). "
        "$\\Delta$F1 reports the interday shift in mean F1 (post-fix minus "
        "baseline). Models with $|\\Delta\\text{F1}|>2\\sigma_{\\text{baseline}}$ "
        "(boldface) showed a behaviour shift between cohorts and are noted in "
        "the discussion.}",
        "\\label{tab:exp1-reasoning-topup}",
        "\\begin{tabular}{lrrrrrr}",
        "\\toprule",
        "Model & $N_{\\text{base}}$ & $N_{\\text{post}}$ & F1 baseline & "
        "F1 post-fix & $\\Delta$F1 & Reasoning tokens \\\\",
        " & & & & & & (median) \\\\",
        "\\midrule",
    ]

    for r in rows:
        slug = r["model"].rsplit("/", 1)[-1]
        name = format_model_name(slug)
        b_mean, b_sd = _mean_sd(r["baseline_f1"])
        t_mean, t_sd = _mean_sd(r["topup_f1"])

        # Interday drift flag: |delta| > 2*baseline_sd
        delta_str = _fmt_delta(b_mean, t_mean)
        if b_mean is not None and t_mean is not None and b_sd:
            delta = t_mean - b_mean
            if abs(delta) > 2 * b_sd:
                delta_str = f"\\textbf{{{delta_str}}}"

        tt_median = (
            statistics.median(r["topup_thinking_tokens"]) if r["topup_thinking_tokens"] else None
        )
        tt_str = _fmt_int_or_dash(int(tt_median) if tt_median is not None else None)

        lines.append(
            " & ".join(
                [
                    name,
                    _fmt_n(len(r["baseline_f1"]), r["baseline_n_total"]),
                    _fmt_n(len(r["topup_f1"]), r["topup_n_total"]),
                    _fmt_f1(b_mean, b_sd, len(r["baseline_f1"])),
                    _fmt_f1(t_mean, t_sd, len(r["topup_f1"])),
                    delta_str,
                    tt_str,
                ]
            )
            + " \\\\"
        )

    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
        ]
    )
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(prog="aedist.tabulate_exp1_reasoning_topup")
    parser.add_argument("--measurements", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(message)s")

    records = []
    with args.measurements.open() as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))

    rows = aggregate(records)
    log.info("Aggregated %d models from %d records", len(rows), len(records))

    tex = generate_table_tex(rows)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(tex + "\n")
    log.info("Wrote %s", args.output)


if __name__ == "__main__":
    main()
