"""Generate self-consistency LaTeX table from self_consistency_summary.json.

Usage:
    python -m aedist.tabulate_self_consistency \\
        --input experiments/outputs/sweep2_rag_consistency/self_consistency_summary.json \\
        --output report/inputs/generated/tab_self_consistency.tex

Reads per-model self-consistency results and emits a LaTeX table showing
single-run medians vs majority/union vote F1, with the two failure regimes
(truncation vs overgeneration) highlighted.
"""

import argparse
import json
import logging
from pathlib import Path

from .tabulate_utils import format_model_name

log = logging.getLogger(__name__)

# Threshold for classifying failure regime: ≥95% means "near-perfect"
_REGIME_THRESHOLD = 0.95


def _regime(r: dict) -> str:
    """Classify a model as truncation-limited or overgeneration-limited.

    Truncation: median precision ~100%, low recall.
    Overgeneration: median recall ~100%, low precision.
    """
    if r["median_precision"] >= _REGIME_THRESHOLD:
        return "truncation"
    if r["median_coverage"] >= _REGIME_THRESHOLD:
        return "overgeneration"
    return "mixed"


def generate_self_consistency_table(results: list[dict]) -> str:
    """Generate LaTeX table from self-consistency summary."""
    results_sorted = sorted(results, key=lambda r: r["median_f1"], reverse=True)

    lines = [
        "% Auto-generated by aedist.tabulate_self_consistency — do not edit",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\caption{Self-consistency: median single-run F1 vs.~majority and union"
        " vote (RAG, 3 runs per model). Regime indicates the dominant failure"
        " mode.}\\label{tab:self-consistency}",
        "\\begin{tabular}{@{}lrrrrl@{}}",
        "\\toprule",
        "Model & Med.~F1 & Maj.~F1 & Union F1 & Best $\\Delta$ & Regime \\\\",
        "\\midrule",
    ]

    for r in results_sorted:
        name = format_model_name(r["model"])
        med_f1 = r["median_f1"] * 100
        maj_f1 = (r.get("majority_f1") or 0) * 100
        union_f1 = (r.get("union_f1") or 0) * 100

        regime = _regime(r)

        if regime == "overgeneration":
            best_delta = maj_f1 - med_f1
        else:
            best_delta = union_f1 - med_f1

        delta_str = f"{best_delta:+.1f}\\%"

        lines.append(
            f"{name} & {med_f1:.1f}\\% & {maj_f1:.1f}\\% & {union_f1:.1f}\\%"
            f" & {delta_str} & {regime} \\\\"
        )

    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
        ]
    )
    return "\n".join(lines) + "\n"


def generate_per_run_table(results: list[dict]) -> str:
    """Generate a detailed per-run LaTeX table.

    Shows individual run F1 scores, number of plants matched, missed, and
    hallucinated for each run.
    """
    lines = [
        "% Auto-generated by aedist.tabulate_self_consistency — do not edit",
        "\\begin{longtable}[]{@{}lrrrrrr@{}}",
        "\\caption{Per-run breakdown: sweep2\\_rag, 5 models $\\times$ 3 runs"
        " (sorted by F1 within each model)."
        " Truncation-limited models show 100\\% precision with varying recall;"
        " overgeneration-limited models show 100\\% recall with varying"
        " precision.}\\label{tab:per-run}\\\\",
        "\\toprule",
        "Model & Plants & Matched & Missed & Halluc. & Recall & F1 \\\\",
        "\\midrule",
        "\\endhead",
        "\\bottomrule",
        "\\endlastfoot",
    ]

    for r in sorted(results, key=lambda r: r["median_f1"], reverse=True):
        name = format_model_name(r["model"])
        n_ref = r.get("n_reference", 163)
        n_runs = r["n_valid_runs"]
        for i in range(n_runs):
            f1 = r["run_f1_scores"][i] * 100
            matched = r["run_n_matched"][i]
            n_sys = r["run_n_system"][i]
            missed = n_ref - matched
            halluc = n_sys - matched
            recall = matched / n_ref * 100 if n_ref > 0 else 0

            run_label = name if i == 0 else ""
            lines.append(
                f"{run_label} & {n_sys}"
                f" & {matched} & {missed} & {halluc}"
                f" & {recall:.1f}\\% & {f1:.1f}\\% \\\\"
            )
        lines.append("\\addlinespace")

    lines.append("\\end{longtable}")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None):
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser(
        description="Generate self-consistency LaTeX tables",
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Path to self_consistency_summary.json",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Path to write tab_self_consistency.tex",
    )
    parser.add_argument(
        "--per-run-output",
        default=None,
        help="Path to write tab_per_run.tex (optional)",
    )
    args = parser.parse_args(argv)

    input_path = Path(args.input)
    output_path = Path(args.output)

    with open(input_path) as f:
        results = json.load(f)

    latex = generate_self_consistency_table(results)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(latex)
    log.info("Wrote %s (%d models)", output_path, len(results))

    if args.per_run_output:
        per_run_path = Path(args.per_run_output)
        per_run_latex = generate_per_run_table(results)
        per_run_path.write_text(per_run_latex)
        log.info("Wrote %s", per_run_path)


if __name__ == "__main__":
    main()
