"""Generate LaTeX \\newcommand macros from measurements.jsonl.

Reads per-run metrics, groups by model slug (stripping -runN suffix
and directory prefix), computes median F1, and emits macros for
the report preamble.

Usage:
    uv run python -m aedist.tabulate_macros \\
        --measurements measurements.jsonl \\
        --output report/inputs/generated/macros.tex
"""

import argparse
import csv
import logging
import statistics
from pathlib import Path

from .stats import bootstrap_ci
from .tabulate_utils import strip_label as slug_from_label

log = logging.getLogger(__name__)


def load_and_summarize(metrics: list[dict]) -> dict[str, dict]:
    """Group metrics by model slug and compute median F1.

    Returns dict mapping slug -> {median_f1, is_local, runs, f1_values}.
    """
    by_model: dict[str, list[float]] = {}
    for entry in metrics:
        slug = slug_from_label(entry["label"])
        by_model.setdefault(slug, []).append(entry["f1"])

    summary = {}
    for slug, f1_values in by_model.items():
        summary[slug] = {
            "median_f1": round(statistics.median(f1_values), 4),
            "is_local": slug.startswith("padme-"),
            "runs": len(f1_values),
            "f1_values": f1_values,
        }
    return summary


def load_census(path: str) -> dict[str, dict]:
    """Load census_bars.csv into the same format as load_and_summarize."""
    summary = {}
    with open(path) as f:
        for row in csv.DictReader(f):
            summary[row["model"]] = {
                "median_f1": float(row["f1"]),
                "is_local": row["local"] == "1",
                "runs": 1,
            }
    return summary


def _prettify(slug: str) -> str:
    """Prettify a model slug for LaTeX display."""
    return slug.replace("-", " ").replace("_", " ").title()


def generate_macros(summary: dict[str, dict]) -> str:
    """Generate LaTeX \\newcommand definitions from model summary."""
    num_models = len(summary)
    local_models = {s: v for s, v in summary.items() if v["is_local"]}
    cloud_models = {s: v for s, v in summary.items() if not v["is_local"]}

    # Best overall
    best_slug = max(summary, key=lambda s: summary[s]["median_f1"])
    best_f1 = summary[best_slug]["median_f1"]

    # Best local (padme- prefix)
    if local_models:
        best_local_slug = max(local_models, key=lambda s: local_models[s]["median_f1"])
        best_local_f1 = local_models[best_local_slug]["median_f1"]
    else:
        best_local_slug = "none"
        best_local_f1 = 0.0

    # Plant range (based on 163 reference plants)
    ref_plants = 163
    f1_values = [v["median_f1"] for v in summary.values()]
    min_plants = round(min(f1_values) * ref_plants)
    max_plants = round(max(f1_values) * ref_plants)

    # Bootstrap CI for best model (if raw values available)
    best_vals = summary[best_slug].get("f1_values", [])
    if len(best_vals) > 1:
        _, ci_lo, ci_hi = bootstrap_ci(best_vals, seed=42)
        best_ci_str = f"{ci_lo * 100:.1f}, {ci_hi * 100:.1f}"
    else:
        best_ci_str = f"{best_f1 * 100:.1f}, {best_f1 * 100:.1f}"

    lines = [
        "% Auto-generated by aedist.tabulate_macros — do not edit",
        f"\\newcommand{{\\NumModelsTested}}{{{num_models}}}",
        f"\\newcommand{{\\NumCloudModels}}{{{len(cloud_models)}}}",
        f"\\newcommand{{\\NumLocalModels}}{{{len(local_models)}}}",
        f"\\newcommand{{\\NumRefPlants}}{{{ref_plants}}}",
        f"\\newcommand{{\\BestModelName}}{{{_prettify(best_slug)}}}",
        f"\\newcommand{{\\BestModelFOne}}{{{best_f1 * 100:.1f}}}",
        f"\\newcommand{{\\BestModelFOneCI}}{{[{best_ci_str}]}}",
        f"\\newcommand{{\\BestLocalName}}{{{_prettify(best_local_slug)}}}",
        f"\\newcommand{{\\BestLocalFOne}}{{{best_local_f1 * 100:.1f}}}",
        f"\\newcommand{{\\MinBaselinePlants}}{{{min_plants}}}",
        f"\\newcommand{{\\MaxBaselinePlants}}{{{max_plants}}}",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser(
        description="Generate LaTeX macros from measurements.jsonl",
    )
    parser.add_argument("--census-csv", help="Census CSV for baseline model counts (slides)")
    parser.add_argument("--output", required=True, help="Path to write macros.tex")
    args = parser.parse_args()

    output_path = Path(args.output)

    if args.census_csv:
        summary = load_census(args.census_csv)
    else:
        from .measurements import load_metrics

        summary = load_and_summarize(load_metrics())
    tex = generate_macros(summary)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(tex)
    log.info("Wrote macros to %s (%d models)", output_path, len(summary))


if __name__ == "__main__":
    main()
