"""Generate LaTeX table comparing FP rates before/after decomposition prompt fix.

Pipeline phase: P3 (analyze & render) — invoked by experiments/render.mk.

Reads reconciliation CSVs directly from rag_per_fuel/ (before) and
rag_per_fuel_v2/ (after) directories. Computes per-run false-positive rates
and mean FP rate per model, organized in two panels.

FP rate = count(match_type == "system_only") / count(match_type != "reference_only")

Ticket: 0068 (decomposition hallucination fix).
"""

from __future__ import annotations

import argparse
import csv
import logging
import re
from pathlib import Path

from .tabulate_utils import format_model_name

log = logging.getLogger(__name__)

_DEFAULT_OUTPUT = Path("report/inputs/generated/tab_decomposition_fix.tex")
# Reconciliation CSVs were gitignored (c14136ff) and never archived. The
# defaults point at the archive dirs where the raw JSONs live, but the
# reconciliation_*.csv files are NOT present — they were a derived product
# of evaluation. The committed tab_decomposition_fix.tex is frozen (0421).
_DEFAULT_BEFORE_DIR = Path("experiments/archive/outputs/rag_per_fuel")
_DEFAULT_AFTER_DIR = Path("experiments/archive/outputs/rag_per_fuel_v2")

_RECON_PATTERN = re.compile(r"^reconciliation_(.+)-run(\d+)\.csv$")


# ---------------------------------------------------------------------------
# FP rate computation
# ---------------------------------------------------------------------------


def fp_rate_from_csv(path: Path) -> tuple[int, float]:
    """Compute FP count and FP rate from a reconciliation CSV.

    Returns (fp_count, fp_rate).  fp_rate = system_only / non_reference_only.
    """
    fp = 0
    total = 0
    with path.open(newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            mt = row["match_type"]
            if mt == "reference_only":
                continue
            total += 1
            if mt == "system_only":
                fp += 1
    rate = fp / total if total > 0 else 0.0
    return fp, rate


def _scan_dir(directory: Path) -> dict[str, dict[int, tuple[int, float]]]:
    """Scan a directory of reconciliation CSVs.

    Returns {model_slug: {run_number: (fp_count, fp_rate)}}.
    """
    result: dict[str, dict[int, tuple[int, float]]] = {}
    if not directory.exists():
        return result
    for path in sorted(directory.glob("reconciliation_*.csv")):
        m = _RECON_PATTERN.match(path.name)
        if not m:
            continue
        model = m.group(1)
        run = int(m.group(2))
        fp_count, fp_rate = fp_rate_from_csv(path)
        result.setdefault(model, {})[run] = (fp_count, fp_rate)
    return result


# ---------------------------------------------------------------------------
# Core computation
# ---------------------------------------------------------------------------


def compute_table(
    before_dir: Path | None = None,
    after_dir: Path | None = None,
) -> dict:
    """Compute FP rate data for before/after panels.

    Returns a dict with keys ``before`` and ``after``, each a list of dicts
    sorted by model slug with keys: model, runs (list of (run_num, fp_count,
    fp_rate)), mean_fp_rate.
    """
    before_dir = before_dir or _DEFAULT_BEFORE_DIR
    after_dir = after_dir or _DEFAULT_AFTER_DIR

    panels = {}
    for panel_name, directory in [("before", before_dir), ("after", after_dir)]:
        data = _scan_dir(directory)
        rows = []
        for model in sorted(data.keys()):
            runs_dict = data[model]
            runs = [(n, fp_count, fp_rate) for n, (fp_count, fp_rate) in sorted(runs_dict.items())]
            rates = [r[2] for r in runs]
            mean_rate = sum(rates) / len(rates) if rates else 0.0
            rows.append(
                {
                    "model": model,
                    "runs": runs,
                    "mean_fp_rate": mean_rate,
                }
            )
        panels[panel_name] = rows
    return panels


# ---------------------------------------------------------------------------
# LaTeX rendering
# ---------------------------------------------------------------------------


def _fmt_pct(x: float) -> str:
    return f"{x * 100:.1f}\\,\\%"


def _fmt_fp_cell(fp_count: int, fp_rate: float) -> str:
    return f"{fp_count} ({_fmt_pct(fp_rate)})"


def render_latex(table: dict) -> str:
    """Render the compute_table() result as a LaTeX table."""
    # Find max runs across all panels to size columns
    max_runs = 0
    for panel in table.values():
        for row in panel:
            max_runs = max(max_runs, len(row["runs"]))
    max_runs = max(max_runs, 3)  # at least 3 columns

    run_cols = " ".join(["r"] * max_runs)

    lines = [
        "% Auto-generated by aedist.tabulate_decomposition_fix — do not edit",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\caption{Taux de faux positifs avant et après correction du prompt de "
        "décomposition~: nombre de FP et taux par run.}\\label{tab:decomposition-fix}",
        f"\\begin{{tabular}}{{@{{}}l{run_cols}r@{{}}}}",
        "\\toprule",
    ]

    # Column headers
    run_headers = " & ".join([f"Run~{i + 1}" for i in range(max_runs)])
    lines.append(f"Modèle & {run_headers} & Moy. FP\\,\\% \\\\")
    lines.append("\\midrule")

    # Panel A: before
    lines.append(
        "\\multicolumn{" + str(max_runs + 2) + "}{l}"
        "{\\textit{Panel A~: avant correction (rag\\_per\\_fuel/)}} \\\\"
    )
    lines.append("\\addlinespace")

    for row in table["before"]:
        name = format_model_name(row["model"])
        cells = [name]
        for i in range(max_runs):
            if i < len(row["runs"]):
                _run_num, fp_count, fp_rate = row["runs"][i]
                cells.append(_fmt_fp_cell(fp_count, fp_rate))
            else:
                cells.append("---")
        cells.append(_fmt_pct(row["mean_fp_rate"]))
        lines.append(" & ".join(cells) + " \\\\")

    lines.append("\\addlinespace")
    lines.append("\\midrule")

    # Panel B: after
    lines.append(
        "\\multicolumn{" + str(max_runs + 2) + "}{l}"
        "{\\textit{Panel B~: après correction (rag\\_per\\_fuel\\_v2/)}} \\\\"
    )
    lines.append("\\addlinespace")

    for row in table["after"]:
        name = format_model_name(row["model"])
        cells = [name]
        for i in range(max_runs):
            if i < len(row["runs"]):
                _run_num, fp_count, fp_rate = row["runs"][i]
                cells.append(_fmt_fp_cell(fp_count, fp_rate))
            else:
                cells.append("---")
        cells.append(_fmt_pct(row["mean_fp_rate"]))
        lines.append(" & ".join(cells) + " \\\\")

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser(
        description="Generate decomposition FP fix comparison LaTeX table",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=_DEFAULT_OUTPUT,
        help=f"Path to write the .tex file (default: {_DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--before-dir",
        type=Path,
        default=_DEFAULT_BEFORE_DIR,
        help="Directory with reconciliation CSVs before fix",
    )
    parser.add_argument(
        "--after-dir",
        type=Path,
        default=_DEFAULT_AFTER_DIR,
        help="Directory with reconciliation CSVs after fix",
    )
    args = parser.parse_args(argv)

    table = compute_table(before_dir=args.before_dir, after_dir=args.after_dir)

    n_before = len(table["before"])
    n_after = len(table["after"])
    if n_before == 0 and n_after == 0:
        log.error("No reconciliation CSVs found in either directory.")
        return

    latex = render_latex(table)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(latex)
    log.info(
        "Wrote %s (%d models before, %d models after)",
        args.output,
        n_before,
        n_after,
    )


if __name__ == "__main__":
    main()
